/*
 *  Armadillo Workflow Platform v1.0
 *  A simple pipeline system for phylogenetic analysis
 *  
 *  Copyright (C) 2009-2011  Etienne Lord, Mickael Leclercq
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package editors;


import workflows.workflow_properties;
import configuration.Config;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

import editor.EditorInterface;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties_dictionnary;

/**
 * Editor of the object properties in the Main Workflow
 * Note: Only called if object doesnt have a Custum Editor
 * @author Etienne Lord
 * @since July 2009
 */
public class ClustalW2Editor extends javax.swing.JDialog implements EditorInterface {

    ////////////////////////////////////////////////////////////////////////////
    /// VARIABLES

    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
   
    ////////////////////////////////////////////////////////////////////////////
    /// CONSTANT
    public final String defaultNameString=" Name";
    
    /////////////////////////////////////////////////////////////////////////
    /// Default Options
    static final boolean default_clustalw2_multi_aln=true;
    static final double default_clustalw2_multi_aln_gop=10;
    static final double default_clustalw2_multi_aln_gep=0.2;
    static final double default_clustalw2_multi_aln_dnatrans=0.5;

    static final boolean default_clustalw2_pair_aln=false;
    static final boolean default_clustalw2_pair_aln_slow=true;
    static final double default_clustalw2_pair_aln_slow_gop=15;
    static final double default_clustalw2_pair_aln_slow_gep=6.66;
    static final boolean default_clustalw2_pair_aln_fast=false;
    static final double default_clustalw2_pair_aln_fast_gp=5.0;
    static final double default_clustalw2_pair_aln_fast_kt=2.0;
    

    /** Creates new form propertiesJDialog */
    public ClustalW2Editor(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
        //connectorinfobox=new ConnectorInfoBox(parent); //--Used to display Connector info
        //--Initialize component
       
    }

    public void setDefaultValues(){
        clustalMultiAln_Button.setSelected(default_clustalw2_multi_aln);
        MultipleAlnFields(default_clustalw2_multi_aln);

        clustalMultiAlnGop_TextField.setText(""+default_clustalw2_multi_aln_gop);
        clustalMultiAlnGep_TextField.setText(""+default_clustalw2_multi_aln_gep);
        clustalMultiAlnDnatrans_TextField.setText(""+default_clustalw2_multi_aln_dnatrans);

        clustalPairwiseAln_Button.setSelected(default_clustalw2_pair_aln);
        pairwiseAlnFields(default_clustalw2_pair_aln);
        clustalPairwiseAlnSlow_Button.setSelected(default_clustalw2_pair_aln_slow);
        clustalPairwiseAlnSlowGop_TextField.setText(""+default_clustalw2_pair_aln_slow_gop);
        clustalPairwiseAlnSlowGep_TextField.setText(""+default_clustalw2_pair_aln_slow_gep);
        
        clustalPairwiseAlnFast_Button.setSelected(default_clustalw2_pair_aln_fast);
        clustalPairwiseAlnFastGp_TextField.setText(""+default_clustalw2_pair_aln_fast_gp);
        clustalPairwiseAlnFastKtuple_TextField.setText(""+default_clustalw2_pair_aln_fast_kt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clustalPairwiseAln_Button = new javax.swing.JRadioButton();
        clustalMultiAln_Button = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        clustalPairwiseAlnSlow_Button = new javax.swing.JRadioButton();
        clustalPairwiseAlnFast_Button = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        clustalPairwiseAlnSlowGop_TextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        clustalPairwiseAlnSlowGep_TextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        clustalPairwiseAlnFastGp_TextField = new javax.swing.JTextField();
        clustalPairwiseAlnFastKtuple_TextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        clustalMultiAlnGop_TextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        clustalMultiAlnGep_TextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        clustalMultiAlnDnatrans_TextField = new javax.swing.JTextField();
        ClosejButton = new javax.swing.JButton();
        run_jButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("Properties");

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Name");

        jButton4.setText("Rename");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(clustalPairwiseAln_Button);
        clustalPairwiseAln_Button.setText("Pairwise alignement");
        clustalPairwiseAln_Button.setToolTipText("<html>\nThe slow-accurate method is fine for short <br/>\nsequences but will be VERY SLOW for many <br/>\n(e.g. >100) long (e.g. >1000 residue) sequences.\n</html>");
        clustalPairwiseAln_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clustalPairwiseAln_ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(clustalMultiAln_Button);
        clustalMultiAln_Button.setSelected(true);
        clustalMultiAln_Button.setText("Complete Multiple alignement (Slow and accurate)");
        clustalMultiAln_Button.setToolTipText("<html>\nAll sequences are compared <br/>\nto each other\n</html>");
        clustalMultiAln_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clustalMultiAln_ButtonActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pairwise Alignment "));

        buttonGroup2.add(clustalPairwiseAlnSlow_Button);
        clustalPairwiseAlnSlow_Button.setSelected(true);
        clustalPairwiseAlnSlow_Button.setText("Slow Accurate");
        clustalPairwiseAlnSlow_Button.setEnabled(false);
        clustalPairwiseAlnSlow_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clustalPairwiseAlnSlow_ButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(clustalPairwiseAlnFast_Button);
        clustalPairwiseAlnFast_Button.setText("Fast Approximate");
        clustalPairwiseAlnFast_Button.setEnabled(false);
        clustalPairwiseAlnFast_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clustalPairwiseAlnFast_ButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Gap Open Penalty");

        clustalPairwiseAlnSlowGop_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalPairwiseAlnSlowGop_TextField.setText("15.0");
        clustalPairwiseAlnSlowGop_TextField.setEnabled(false);
        clustalPairwiseAlnSlowGop_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalPairwiseAlnSlowGop_TextFieldFocusLost(evt);
            }
        });

        jLabel17.setText("Gap Extension Penalty");

        clustalPairwiseAlnSlowGep_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalPairwiseAlnSlowGep_TextField.setText("6.66");
        clustalPairwiseAlnSlowGep_TextField.setEnabled(false);
        clustalPairwiseAlnSlowGep_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalPairwiseAlnSlowGep_TextFieldFocusLost(evt);
            }
        });

        jLabel18.setText("Gap Penalty");

        clustalPairwiseAlnFastGp_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalPairwiseAlnFastGp_TextField.setText("5.0");
        clustalPairwiseAlnFastGp_TextField.setEnabled(false);
        clustalPairwiseAlnFastGp_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalPairwiseAlnFastGp_TextFieldFocusLost(evt);
            }
        });

        clustalPairwiseAlnFastKtuple_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalPairwiseAlnFastKtuple_TextField.setText("2.0");
        clustalPairwiseAlnFastKtuple_TextField.setEnabled(false);
        clustalPairwiseAlnFastKtuple_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalPairwiseAlnFastKtuple_TextFieldFocusLost(evt);
            }
        });

        jLabel19.setText("K-tuple (word) size");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(clustalPairwiseAlnFast_Button)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clustalPairwiseAlnFastKtuple_TextField)
                            .addComponent(clustalPairwiseAlnFastGp_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(clustalPairwiseAlnSlow_Button)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clustalPairwiseAlnSlowGop_TextField)
                            .addComponent(clustalPairwiseAlnSlowGep_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clustalPairwiseAlnSlow_Button)
                        .addComponent(jLabel16))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(clustalPairwiseAlnSlowGop_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clustalPairwiseAlnSlowGep_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clustalPairwiseAlnFast_Button)
                        .addComponent(jLabel18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel19))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(clustalPairwiseAlnFastGp_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clustalPairwiseAlnFastKtuple_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Complete Multiple Alignment"));

        jLabel20.setText("Gap Opening Penalty (0.0-100.0) : ");

        clustalMultiAlnGop_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalMultiAlnGop_TextField.setText("10.0");
        clustalMultiAlnGop_TextField.setToolTipText("The penalty for opening a gap in the alignment. Increasing the gap opening penalty will make gaps less frequent. Gap open penalty default = 10 (0.0-100.0) ");
        clustalMultiAlnGop_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalMultiAlnGop_TextFieldFocusLost(evt);
            }
        });

        jLabel21.setText("Gap Extension Penalty (0.0-10.0) :");

        clustalMultiAlnGep_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalMultiAlnGep_TextField.setText("0.2");
        clustalMultiAlnGep_TextField.setToolTipText("The penalty for extending a gap. Increasing the gap extension penalty will make gaps shorter. Terminal gaps are not penalised. Gap open penalty default = 0.2 (0.0-10.0) ");
        clustalMultiAlnGep_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalMultiAlnGep_TextFieldFocusLost(evt);
            }
        });

        jLabel22.setText("DNA Transition Weight (0.0-1.0) :");

        clustalMultiAlnDnatrans_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clustalMultiAlnDnatrans_TextField.setText("0.5");
        clustalMultiAlnDnatrans_TextField.setToolTipText("The Transitions Weight gives transitions (A <--> G or C <--> T  i.e. purine-purine or pyrimidine-pyrimidine substitutions) a weight between 0 and 1; a weight of zero means that the transitions are scored as mismatches, while a weight of 1 gives the transitions the match score. For distantly related DNA sequences, the weight should be near to zero; for closely related sequences it can be useful to assign a higher score. Default = 0.5 (0.0-1.0) ");
        clustalMultiAlnDnatrans_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clustalMultiAlnDnatrans_TextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clustalMultiAlnDnatrans_TextField)
                    .addComponent(clustalMultiAlnGep_TextField)
                    .addComponent(clustalMultiAlnGop_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clustalMultiAlnGop_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clustalMultiAlnGep_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clustalMultiAlnDnatrans_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clustalPairwiseAln_Button)
            .addComponent(clustalMultiAln_Button)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(clustalMultiAln_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clustalPairwiseAln_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        ClosejButton.setText("<html><b>Close</b></html>");
        ClosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButtonActionPerformed(evt);
            }
        });

        run_jButton.setText("Run");
        run_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButtonActionPerformed(evt);
            }
        });

        jButton8.setText("Stop");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset default values");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run_jButton)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ClustalW2", jPanel9);

        jButton7.setText("?");
        jButton7.setToolTipText("Help / Informations");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButtonActionPerformed
        //-- 2. Close dialog
        this.setVisible(false);
}//GEN-LAST:event_ClosejButtonActionPerformed

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
      
}//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       properties.put("Name", this.NamejTextField.getText());

       parent_workflow.updateCurrentWorkflow(properties);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clustalPairwiseAln_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clustalPairwiseAln_ButtonActionPerformed
        properties.put("PairwiseAlignment", clustalPairwiseAln_Button.isSelected());
        this.pairwiseAlnFields(true);
        this.MultipleAlnFields(false);
            
}//GEN-LAST:event_clustalPairwiseAln_ButtonActionPerformed

    private void clustalMultiAln_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clustalMultiAln_ButtonActionPerformed
        properties.put("MultiAlignment", clustalMultiAln_Button.isSelected());
        this.pairwiseAlnFields(false);
        this.MultipleAlnFields(true);
}//GEN-LAST:event_clustalMultiAln_ButtonActionPerformed

    private void clustalPairwiseAlnSlow_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnSlow_ButtonActionPerformed
        properties.put("PairwiseAlignmentSlow", clustalPairwiseAlnSlow_Button.isSelected());

}//GEN-LAST:event_clustalPairwiseAlnSlow_ButtonActionPerformed

    private void clustalPairwiseAlnFast_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnFast_ButtonActionPerformed
        properties.put("PairwiseAlignmentFast", clustalPairwiseAlnFast_Button.isSelected());

}//GEN-LAST:event_clustalPairwiseAlnFast_ButtonActionPerformed

    private void clustalPairwiseAlnSlowGop_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnSlowGop_TextFieldFocusLost
        properties.put("PairwiseAlignmentSlowGop", clustalPairwiseAlnSlowGop_TextField.getText());
        if (Double.valueOf(this.clustalPairwiseAlnSlowGop_TextField.getText())<0||
                Double.valueOf(clustalPairwiseAlnSlowGop_TextField.getText())>100){
//            MessageError("Bad value at gap open penalty in ClustalW2 slow accurate " +
//                    "pairwise alignment. Value must be included between 0 and 100", "");
        }else {
//            this.Message("","");
        }
}//GEN-LAST:event_clustalPairwiseAlnSlowGop_TextFieldFocusLost

    private void clustalPairwiseAlnSlowGep_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnSlowGep_TextFieldFocusLost
        properties.put("PairwiseAlignmentSlowGep", clustalPairwiseAlnSlowGep_TextField.getText());
        if (Double.valueOf(this.clustalPairwiseAlnSlowGep_TextField.getText())<0||
                Double.valueOf(clustalPairwiseAlnSlowGep_TextField.getText())>100){
//            MessageError("Bad value at gap extension penalty in ClustalW2 slow " +
//                    "accurate pairwise alignment. Value must be included between 0 and 10", "");
            run_jButton.setEnabled(false);
        }else{
//            Message("","");
            run_jButton.setEnabled(true);
        }
}//GEN-LAST:event_clustalPairwiseAlnSlowGep_TextFieldFocusLost

    private void clustalPairwiseAlnFastGp_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnFastGp_TextFieldFocusLost
         properties.put("PairwiseAlignmentFastGp", clustalPairwiseAlnFastGp_TextField.getText());

         if (Integer.valueOf(this.clustalPairwiseAlnFastGp_TextField.getText())<1||
                    Integer.valueOf(this.clustalPairwiseAlnFastGp_TextField.getText())>500){
//                MessageError("Bad value at gap penalty in ClustalW2 fast approximate pairwise alignment. " +
//                        "Value must be included between 1 and 500", "");
                run_jButton.setEnabled(false);
            }else {
//                Message("","");
                this.run_jButton.setEnabled(true);
            }

}//GEN-LAST:event_clustalPairwiseAlnFastGp_TextFieldFocusLost

    private void clustalPairwiseAlnFastKtuple_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalPairwiseAlnFastKtuple_TextFieldFocusLost
         properties.put("PairwiseAlignmentFastKtuple", clustalPairwiseAlnFastKtuple_TextField.getText());
            if (Double.valueOf(this.clustalPairwiseAlnFastKtuple_TextField.getText()) < 1 ||
                    Double.valueOf(this.clustalPairwiseAlnFastKtuple_TextField.getText()) > 4) {
//                MessageError("Bad value at K-tuple in ClustalW2 fast " +
//                        "approximate pairwise alignment. Value must be included between 1 and 4","");
                this.run_jButton.setEnabled(false);
            } else {
//                this.Message("","");
                this.run_jButton.setEnabled(true);
            }

}//GEN-LAST:event_clustalPairwiseAlnFastKtuple_TextFieldFocusLost

    private void clustalMultiAlnDnatrans_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalMultiAlnDnatrans_TextFieldFocusLost
        properties.put("MultipleAlignmentDnaTransition", clustalMultiAlnDnatrans_TextField.getText());
        if (Double.valueOf(this.clustalMultiAlnDnatrans_TextField.getText())<0||
                Double.valueOf(clustalMultiAlnDnatrans_TextField.getText())>1){
//            MessageError("Bad value at DNA Transitions Weight in ClustalW2 Complete " +
//                    "multi alignment. Value must be included between 0 and 1", "");
            this.run_jButton.setEnabled(false);
        }else{
//            this.Message("","");
            this.run_jButton.setEnabled(true);
        }
}//GEN-LAST:event_clustalMultiAlnDnatrans_TextFieldFocusLost

    private void clustalMultiAlnGep_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalMultiAlnGep_TextFieldFocusLost
        properties.put("MultipleAlignmentGep",clustalMultiAlnGep_TextField.getText());
        if (Double.valueOf(this.clustalMultiAlnGep_TextField.getText())<0||
                Double.valueOf(clustalMultiAlnGep_TextField.getText())>100){
//            MessageError("Bad value at gap extension penalty in ClustalW2 Complete " +
//                    "multi alignment. Value must be included between 0 and 10", "");

            this.run_jButton.setEnabled(false);
        }else{
//            this.Message("","");
            this.run_jButton.setEnabled(true);
        }
}//GEN-LAST:event_clustalMultiAlnGep_TextFieldFocusLost

    private void clustalMultiAlnGop_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clustalMultiAlnGop_TextFieldFocusLost
        properties.put("MultipleAlignmentGop",clustalMultiAlnGop_TextField.getText());
}//GEN-LAST:event_clustalMultiAlnGop_TextFieldFocusLost

    private void run_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButtonActionPerformed
        if(properties.isSet("ClassName")) {
           this.parent_workflow.workflow.updateDependance();
           programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
           prog.Run(properties);
        }
}//GEN-LAST:event_run_jButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        properties.put("Status", Config.status_nothing);
        properties.killThread();
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
}//GEN-LAST:event_jButton7ActionPerformed

    /**
     * Enable or disable fields of Multiple Alignment
     * @param enabled
     */
    public void MultipleAlnFields(boolean enabled){
        this.clustalMultiAlnDnatrans_TextField.setEnabled(enabled);
        this.clustalMultiAlnGep_TextField.setEnabled(enabled);
        this.clustalMultiAlnGop_TextField.setEnabled(enabled);
    }

    /**
     * Enable or disable fields of pairwise Alignment
     * @param enabled
     */
    public void pairwiseAlnFields(boolean enabled){
        this.clustalPairwiseAlnFastGp_TextField.setEnabled(enabled);
        this.clustalPairwiseAlnFastKtuple_TextField.setEnabled(enabled);
        this.clustalPairwiseAlnFast_Button.setEnabled(enabled);
        this.clustalPairwiseAlnSlowGep_TextField.setEnabled(enabled);
        this.clustalPairwiseAlnSlowGop_TextField.setEnabled(enabled);
        this.clustalPairwiseAlnSlow_Button.setEnabled(enabled);
    }

   

  
    /**
     * This set the Properties
     * @param properties
     */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());      
        //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        setSettingForProperties();
        
    }

     /**
     * This set the Properties
     * @param properties
     */
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
       setSettingForProperties();
     
    }

      

    /**
     * This set the different setting corresponding to the current properties
     */
    public void setSettingForProperties() {
           this.NamejTextField.setText(properties.getName());
     }

    ///////////////////////////////////////////////////////////////////////////
    /// DISPLAY MAIN FUNCTION

    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);      
        // Set position 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
					(screenSize.height-d.height)/2);
        this.setProperties(properties);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

   public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds()); 
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
           Config.log("Unable to save "+filename+" dialog image");
        }            
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClosejButton;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField clustalMultiAlnDnatrans_TextField;
    private javax.swing.JTextField clustalMultiAlnGep_TextField;
    private javax.swing.JTextField clustalMultiAlnGop_TextField;
    private javax.swing.JRadioButton clustalMultiAln_Button;
    private javax.swing.JTextField clustalPairwiseAlnFastGp_TextField;
    private javax.swing.JTextField clustalPairwiseAlnFastKtuple_TextField;
    private javax.swing.JRadioButton clustalPairwiseAlnFast_Button;
    private javax.swing.JTextField clustalPairwiseAlnSlowGep_TextField;
    private javax.swing.JTextField clustalPairwiseAlnSlowGop_TextField;
    private javax.swing.JRadioButton clustalPairwiseAlnSlow_Button;
    private javax.swing.JRadioButton clustalPairwiseAln_Button;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton run_jButton;
    // End of variables declaration//GEN-END:variables



}
