/**
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package editors;

import configuration.Config;
import configuration.Util;
import editor.EditorInterface;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author : JG
 * @Date   : Feb 2016
 */

public class EMBOSS_est2genomeEditors extends javax.swing.JDialog implements EditorInterface  {

    /**
     * Creates new form EMBOSS_est2genomeEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected = "";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow  parent_workflow;

    public final String defaultNameString="Name";
    static final boolean default_map=true;
    public static HashMap<JCheckBox,JSpinner> DictBoxSpinner = new HashMap<JCheckBox,JSpinner>();
    public static HashMap<JCheckBox,JTextField> DictBoxTextField = new HashMap<JCheckBox,JTextField>();
    public static HashMap<JCheckBox,JComboBox> DictBoxComboBox = new HashMap<JCheckBox,JComboBox>();
    public static HashMap<JRadioButton,JSpinner> DictRadioButtonSpinner = new HashMap<JRadioButton,JSpinner>();
    public static HashMap<JRadioButton,JTextField> DictRadioButtonTextField = new HashMap<JRadioButton,JTextField>();
    public static ArrayList<HashMap> listDicts = new ArrayList<HashMap>();

    public EMBOSS_est2genomeEditors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Buttons = new javax.swing.ButtonGroup();
        docker_jButton = new javax.swing.JButton();
        EMBOSS_est2genomeEditors2 = new javax.swing.JTabbedPane();
        general_jPanel1 = new javax.swing.JPanel();
        name_jLabel = new javax.swing.JLabel();
        name_jTextField = new javax.swing.JTextField();
        default_RButton = new javax.swing.JRadioButton();
        Advanced_Options_RButton = new javax.swing.JRadioButton();
        stop_jButton = new javax.swing.JButton();
        reset_jButton = new javax.swing.JButton();
        run_jButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sq_panel = new javax.swing.JPanel();
        Sq_match_Box = new javax.swing.JCheckBox();
        Sq_match_Box_IntValue = new javax.swing.JSpinner();
        Sq_mismatch_Box = new javax.swing.JCheckBox();
        Sq_mismatch_Box_IntValue = new javax.swing.JSpinner();
        Sq_gappenalty_Box = new javax.swing.JCheckBox();
        Sq_gappenalty_Box_IntValue = new javax.swing.JSpinner();
        Sq_intronpenalty_Box = new javax.swing.JCheckBox();
        Sq_intronpenalty_Box_IntValue = new javax.swing.JSpinner();
        Sq_splicepenalty_Box = new javax.swing.JCheckBox();
        Sq_splicepenalty_Box_IntValue = new javax.swing.JSpinner();
        Sq_minscore_Box = new javax.swing.JCheckBox();
        Sq_minscore_Box_IntValue = new javax.swing.JSpinner();
        Sq_reverse_Box = new javax.swing.JCheckBox();
        Sq_reverse_Box_BooValue = new javax.swing.JSpinner();
        Sq_usesplice_Box = new javax.swing.JCheckBox();
        Sq_usesplice_Box_BooValue = new javax.swing.JSpinner();
        Sq_mode_Box = new javax.swing.JCheckBox();
        Sq_mode_Box_List = new javax.swing.JComboBox();
        Sq_best_Box = new javax.swing.JCheckBox();
        Sq_best_Box_BooValue = new javax.swing.JSpinner();
        Sq_space_Box = new javax.swing.JCheckBox();
        Sq_space_Box_FloValue = new javax.swing.JSpinner();
        Sq_shuffle_Box = new javax.swing.JCheckBox();
        Sq_shuffle_Box_IntValue = new javax.swing.JSpinner();
        Sq_seed_Box = new javax.swing.JCheckBox();
        Sq_seed_Box_IntValue = new javax.swing.JSpinner();
        Sq_align_Box = new javax.swing.JCheckBox();
        Sq_align_Box_BooValue = new javax.swing.JSpinner();
        Sq_width_Box = new javax.swing.JCheckBox();
        Sq_width_Box_IntValue = new javax.swing.JSpinner();
        close_jButton = new javax.swing.JButton();
        how_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        docker_jButton.setText("Docker Editor");
        docker_jButton.setName("docker_jButton"); // NOI18N
        docker_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docker_jButton_ActionPerformed(evt);
            }
        });

        EMBOSS_est2genomeEditors2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                EMBOSS_est2genomeEditors2ComponentShown(evt);
            }
        });

        general_jPanel1.setName("general_jPanel1"); // NOI18N
        general_jPanel1.setPreferredSize(new java.awt.Dimension(459, 400));

        name_jLabel.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        name_jLabel.setText("(re)Name");
        name_jLabel.setName("name_jLabel"); // NOI18N

        name_jTextField.setText("EMBOSS_est2genome");
        name_jTextField.setName("name_jTextField"); // NOI18N
        name_jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_jTextFieldFocusLost(evt);
            }
        });
        name_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_jTextField_ActionPerformed(evt);
            }
        });

        Menu_Buttons.add(default_RButton);
        default_RButton.setText("default");
        default_RButton.setName("default_RButton"); // NOI18N
        default_RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_RButton_ActionPerformed(evt);
            }
        });

        Menu_Buttons.add(Advanced_Options_RButton);
        Advanced_Options_RButton.setText("Advanced Options");
        Advanced_Options_RButton.setName("Advanced_Options_RButton"); // NOI18N
        Advanced_Options_RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Advanced_Options_RButton_ActionPerformed(evt);
            }
        });

        stop_jButton.setForeground(new java.awt.Color(255, 0, 0));
        stop_jButton.setText("Stop");
        stop_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setName("stop_jButton"); // NOI18N
        stop_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        stop_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton_ActionPerformed(evt);
            }
        });

        reset_jButton.setForeground(new java.awt.Color(255, 116, 0));
        reset_jButton.setText("Reset");
        reset_jButton.setName("reset_jButton"); // NOI18N
        reset_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton_ActionPerformed(evt);
            }
        });

        run_jButton.setForeground(new java.awt.Color(0, 255, 3));
        run_jButton.setText("Run");
        run_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        run_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        run_jButton.setName("run_jButton"); // NOI18N
        run_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        run_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton_ActionPerformed(evt);
            }
        });

        Sq_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Standard_qualifiers"));

        Sq_match_Box.setText("match");
        Sq_match_Box.setName("Sq_match_Box"); // NOI18N
        Sq_match_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_match_Box_ActionPerformed(evt);
            }
        });

        Sq_match_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(1, -2147483648, 2147483647, 1));
        Sq_match_Box_IntValue.setName("Sq_match_Box_IntValue"); // NOI18N
        Sq_match_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_match_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_match_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_mismatch_Box.setText("mismatch");
        Sq_mismatch_Box.setName("Sq_mismatch_Box"); // NOI18N
        Sq_mismatch_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_mismatch_Box_ActionPerformed(evt);
            }
        });

        Sq_mismatch_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(1, -2147483648, 2147483647, 1));
        Sq_mismatch_Box_IntValue.setName("Sq_mismatch_Box_IntValue"); // NOI18N
        Sq_mismatch_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_mismatch_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_mismatch_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_gappenalty_Box.setText("gappenalty");
        Sq_gappenalty_Box.setName("Sq_gappenalty_Box"); // NOI18N
        Sq_gappenalty_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_gappenalty_Box_ActionPerformed(evt);
            }
        });

        Sq_gappenalty_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(2, -2147483648, 2147483647, 1));
        Sq_gappenalty_Box_IntValue.setName("Sq_gappenalty_Box_IntValue"); // NOI18N
        Sq_gappenalty_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_gappenalty_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_gappenalty_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_intronpenalty_Box.setText("intronpenalty");
        Sq_intronpenalty_Box.setName("Sq_intronpenalty_Box"); // NOI18N
        Sq_intronpenalty_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_intronpenalty_Box_ActionPerformed(evt);
            }
        });

        Sq_intronpenalty_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(40, -2147483648, 2147483647, 1));
        Sq_intronpenalty_Box_IntValue.setName("Sq_intronpenalty_Box_IntValue"); // NOI18N
        Sq_intronpenalty_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_intronpenalty_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_intronpenalty_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_splicepenalty_Box.setText("splicepenalty");
        Sq_splicepenalty_Box.setName("Sq_splicepenalty_Box"); // NOI18N
        Sq_splicepenalty_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_splicepenalty_Box_ActionPerformed(evt);
            }
        });

        Sq_splicepenalty_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(20, -2147483648, 2147483647, 1));
        Sq_splicepenalty_Box_IntValue.setName("Sq_splicepenalty_Box_IntValue"); // NOI18N
        Sq_splicepenalty_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_splicepenalty_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_splicepenalty_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_minscore_Box.setText("minscore");
        Sq_minscore_Box.setName("Sq_minscore_Box"); // NOI18N
        Sq_minscore_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_minscore_Box_ActionPerformed(evt);
            }
        });

        Sq_minscore_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(30, -2147483648, 2147483647, 1));
        Sq_minscore_Box_IntValue.setName("Sq_minscore_Box_IntValue"); // NOI18N
        Sq_minscore_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_minscore_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_minscore_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_reverse_Box.setText("reverse");
        Sq_reverse_Box.setName("Sq_reverse_Box"); // NOI18N
        Sq_reverse_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_reverse_Box_ActionPerformed(evt);
            }
        });

        Sq_reverse_Box_BooValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        Sq_reverse_Box_BooValue.setName("Sq_reverse_Box_BooValue"); // NOI18N
        Sq_reverse_Box_BooValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_reverse_Box_BooValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_reverse_Box_BooValue_StateChanged(evt);
            }
        });

        Sq_usesplice_Box.setText("usesplice");
        Sq_usesplice_Box.setName("Sq_usesplice_Box"); // NOI18N
        Sq_usesplice_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_usesplice_Box_ActionPerformed(evt);
            }
        });

        Sq_usesplice_Box_BooValue.setModel(new javax.swing.SpinnerNumberModel(1, 0, 1, 1));
        Sq_usesplice_Box_BooValue.setName("Sq_usesplice_Box_BooValue"); // NOI18N
        Sq_usesplice_Box_BooValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_usesplice_Box_BooValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_usesplice_Box_BooValue_StateChanged(evt);
            }
        });

        Sq_mode_Box.setText("mode");
        Sq_mode_Box.setName("Sq_mode_Box"); // NOI18N
        Sq_mode_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_mode_Box_ActionPerformed(evt);
            }
        });

        Sq_mode_Box_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "both", "forward", "reverse" }));
        Sq_mode_Box_List.setName("Sq_mode_Box_List"); // NOI18N
        Sq_mode_Box_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_mode_Box_List_ActionPerformed(evt);
            }
        });

        Sq_best_Box.setText("best");
        Sq_best_Box.setName("Sq_best_Box"); // NOI18N
        Sq_best_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_best_Box_ActionPerformed(evt);
            }
        });

        Sq_best_Box_BooValue.setModel(new javax.swing.SpinnerNumberModel(1, 0, 1, 1));
        Sq_best_Box_BooValue.setName("Sq_best_Box_BooValue"); // NOI18N
        Sq_best_Box_BooValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_best_Box_BooValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_best_Box_BooValue_StateChanged(evt);
            }
        });

        Sq_space_Box.setText("space");
        Sq_space_Box.setName("Sq_space_Box"); // NOI18N
        Sq_space_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_space_Box_ActionPerformed(evt);
            }
        });

        Sq_space_Box_FloValue.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(-1.0E14f), Float.valueOf(1.0E14f), Float.valueOf(1.0f)));
        Sq_space_Box_FloValue.setName("Sq_space_Box_FloValue"); // NOI18N
        Sq_space_Box_FloValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_space_Box_FloValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_space_Box_FloValue_StateChanged(evt);
            }
        });

        Sq_shuffle_Box.setText("shuffle");
        Sq_shuffle_Box.setName("Sq_shuffle_Box"); // NOI18N
        Sq_shuffle_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_shuffle_Box_ActionPerformed(evt);
            }
        });

        Sq_shuffle_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(0, -2147483648, 2147483647, 1));
        Sq_shuffle_Box_IntValue.setName("Sq_shuffle_Box_IntValue"); // NOI18N
        Sq_shuffle_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_shuffle_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_shuffle_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_seed_Box.setText("seed");
        Sq_seed_Box.setName("Sq_seed_Box"); // NOI18N
        Sq_seed_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_seed_Box_ActionPerformed(evt);
            }
        });

        Sq_seed_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(20825, -2147483648, 2147483647, 100));
        Sq_seed_Box_IntValue.setName("Sq_seed_Box_IntValue"); // NOI18N
        Sq_seed_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_seed_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_seed_Box_IntValue_StateChanged(evt);
            }
        });

        Sq_align_Box.setText("align");
        Sq_align_Box.setName("Sq_align_Box"); // NOI18N
        Sq_align_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_align_Box_ActionPerformed(evt);
            }
        });

        Sq_align_Box_BooValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        Sq_align_Box_BooValue.setName("Sq_align_Box_BooValue"); // NOI18N
        Sq_align_Box_BooValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_align_Box_BooValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_align_Box_BooValue_StateChanged(evt);
            }
        });

        Sq_width_Box.setText("width");
        Sq_width_Box.setName("Sq_width_Box"); // NOI18N
        Sq_width_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sq_width_Box_ActionPerformed(evt);
            }
        });

        Sq_width_Box_IntValue.setModel(new javax.swing.SpinnerNumberModel(50, -2147483648, 2147483647, 1));
        Sq_width_Box_IntValue.setName("Sq_width_Box_IntValue"); // NOI18N
        Sq_width_Box_IntValue.setPreferredSize(new java.awt.Dimension(115, 28));
        Sq_width_Box_IntValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sq_width_Box_IntValue_StateChanged(evt);
            }
        });

        javax.swing.GroupLayout Sq_panelLayout = new javax.swing.GroupLayout(Sq_panel);
        Sq_panel.setLayout(Sq_panelLayout);
        Sq_panelLayout.setHorizontalGroup(
            Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sq_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sq_panelLayout.createSequentialGroup()
                        .addComponent(Sq_align_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sq_align_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sq_panelLayout.createSequentialGroup()
                        .addComponent(Sq_width_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sq_width_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sq_panelLayout.createSequentialGroup()
                        .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sq_intronpenalty_Box)
                            .addComponent(Sq_match_Box)
                            .addComponent(Sq_mismatch_Box)
                            .addComponent(Sq_gappenalty_Box)
                            .addComponent(Sq_splicepenalty_Box)
                            .addComponent(Sq_minscore_Box)
                            .addComponent(Sq_reverse_Box)
                            .addComponent(Sq_usesplice_Box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Sq_panelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sq_match_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sq_mismatch_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sq_gappenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sq_intronpenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Sq_reverse_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sq_splicepenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sq_minscore_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sq_usesplice_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Sq_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Sq_panelLayout.createSequentialGroup()
                                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sq_mode_Box)
                                    .addComponent(Sq_best_Box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sq_best_Box_BooValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sq_mode_Box_List, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Sq_panelLayout.createSequentialGroup()
                                .addComponent(Sq_space_Box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sq_space_Box_FloValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Sq_panelLayout.createSequentialGroup()
                                .addComponent(Sq_seed_Box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sq_seed_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Sq_panelLayout.createSequentialGroup()
                                .addComponent(Sq_shuffle_Box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sq_shuffle_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        Sq_panelLayout.setVerticalGroup(
            Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sq_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_match_Box)
                    .addComponent(Sq_match_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_mismatch_Box)
                    .addComponent(Sq_mismatch_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_gappenalty_Box)
                    .addComponent(Sq_gappenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_intronpenalty_Box)
                    .addComponent(Sq_intronpenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_splicepenalty_Box)
                    .addComponent(Sq_splicepenalty_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_minscore_Box)
                    .addComponent(Sq_minscore_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sq_reverse_Box_BooValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sq_reverse_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_usesplice_Box)
                    .addComponent(Sq_usesplice_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_mode_Box_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sq_mode_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_best_Box)
                    .addComponent(Sq_best_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_space_Box)
                    .addComponent(Sq_space_Box_FloValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_shuffle_Box)
                    .addComponent(Sq_shuffle_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_seed_Box)
                    .addComponent(Sq_seed_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_align_Box)
                    .addComponent(Sq_align_Box_BooValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sq_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sq_width_Box)
                    .addComponent(Sq_width_Box_IntValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Sq_match_Box.getAccessibleContext().setAccessibleDescription("Score for matching two bases");
        Sq_match_Box_IntValue.getAccessibleContext().setAccessibleDescription("Score for matching two bases");
        Sq_mismatch_Box.getAccessibleContext().setAccessibleDescription("Cost for mismatching two bases");
        Sq_mismatch_Box_IntValue.getAccessibleContext().setAccessibleDescription("Cost for mismatching two bases");
        Sq_gappenalty_Box.getAccessibleContext().setAccessibleDescription("Cost for deleting a single base in either sequence, excluding introns");
        Sq_gappenalty_Box_IntValue.getAccessibleContext().setAccessibleDescription("Cost for deleting a single base in either sequence, excluding introns");
        Sq_intronpenalty_Box.getAccessibleContext().setAccessibleDescription("Cost for an intron, independent of length.");
        Sq_intronpenalty_Box_IntValue.getAccessibleContext().setAccessibleDescription("Cost for an intron, independent of length.");
        Sq_splicepenalty_Box.getAccessibleContext().setAccessibleDescription("Cost for an intron, independent of length and starting/ending on donor-acceptor sites");
        Sq_splicepenalty_Box_IntValue.getAccessibleContext().setAccessibleDescription("Cost for an intron, independent of length and starting/ending on donor-acceptor sites");
        Sq_minscore_Box.getAccessibleContext().setAccessibleDescription("Exclude alignments with scores below this threshold score.");
        Sq_minscore_Box_IntValue.getAccessibleContext().setAccessibleDescription("Exclude alignments with scores below this threshold score.");
        Sq_reverse_Box.getAccessibleContext().setAccessibleDescription("Reverse the orientation of the EST sequence");
        Sq_reverse_Box_BooValue.getAccessibleContext().setAccessibleDescription("Reverse the orientation of the EST sequence");
        Sq_usesplice_Box.getAccessibleContext().setAccessibleDescription("Use donor and acceptor splice sites. If you want to ignore donor-acceptor sites then set this to be false.");
        Sq_usesplice_Box_BooValue.getAccessibleContext().setAccessibleDescription("Use donor and acceptor splice sites. If you want to ignore donor-acceptor sites then set this to be false.");
        Sq_mode_Box.getAccessibleContext().setAccessibleDescription("This determines the comparison mode. The default value is 'both', in which case both strands of the est are compared assuming a forward gene direction (ie GT/AG splice sites), and the best comparison redone assuming a reversed (CT/AC) gene splicing direction. The other allowed modes are 'forward', when just the forward strand is searched, and 'reverse', ditto for the reverse strand.");
        Sq_mode_Box_List.getAccessibleContext().setAccessibleDescription("This determines the comparison mode. The default value is 'both', in which case both strands of the est are compared assuming a forward gene direction (ie GT/AG splice sites), and the best comparison redone assuming a reversed (CT/AC) gene splicing direction. The other allowed modes are 'forward', when just the forward strand is searched, and 'reverse', ditto for the reverse strand.");
        Sq_best_Box.getAccessibleContext().setAccessibleDescription("You can print out all comparisons instead of just the best one by setting this to be false.");
        Sq_best_Box_BooValue.getAccessibleContext().setAccessibleDescription("You can print out all comparisons instead of just the best one by setting this to be false.");
        Sq_space_Box.getAccessibleContext().setAccessibleDescription("For linear-space recursion. If product of sequence lengths divided by 4 exceeds this then a divide-and-conquer strategy is used to control the memory requirements. In this way very long sequences can be aligned. If you have a machine with plenty of memory you can raise this parameter (but do not exceed the machine's physical RAM)");
        Sq_space_Box_FloValue.getAccessibleContext().setAccessibleDescription("For linear-space recursion. If product of sequence lengths divided by 4 exceeds this then a divide-and-conquer strategy is used to control the memory requirements. In this way very long sequences can be aligned. If you have a machine with plenty of memory you can raise this parameter (but do not exceed the machine's physical RAM)");
        Sq_shuffle_Box.getAccessibleContext().setAccessibleDescription("Shuffle.");
        Sq_shuffle_Box_IntValue.getAccessibleContext().setAccessibleDescription("Shuffle.");
        Sq_seed_Box.getAccessibleContext().setAccessibleDescription("Random number seed");
        Sq_seed_Box_IntValue.getAccessibleContext().setAccessibleDescription("Random number seed");
        Sq_align_Box.getAccessibleContext().setAccessibleDescription("Show the alignment. The alignment includes the first and last 5 bases of each intron, together with the intron width. The direction of splicing is indicated by angle brackets (forward or reverse) or ???? (unknown).");
        Sq_align_Box_BooValue.getAccessibleContext().setAccessibleDescription("Show the alignment. The alignment includes the first and last 5 bases of each intron, together with the intron width. The direction of splicing is indicated by angle brackets (forward or reverse) or ???? (unknown).");
        Sq_width_Box.getAccessibleContext().setAccessibleDescription("Alignment width");
        Sq_width_Box_IntValue.getAccessibleContext().setAccessibleDescription("Alignment width");

        jScrollPane1.setViewportView(Sq_panel);

        javax.swing.GroupLayout general_jPanel1Layout = new javax.swing.GroupLayout(general_jPanel1);
        general_jPanel1.setLayout(general_jPanel1Layout);
        general_jPanel1Layout.setHorizontalGroup(
            general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(general_jPanel1Layout.createSequentialGroup()
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(general_jPanel1Layout.createSequentialGroup()
                        .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(general_jPanel1Layout.createSequentialGroup()
                                .addComponent(default_RButton)
                                .addGap(18, 18, 18)
                                .addComponent(Advanced_Options_RButton))
                            .addGroup(general_jPanel1Layout.createSequentialGroup()
                                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reset_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(general_jPanel1Layout.createSequentialGroup()
                                        .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        general_jPanel1Layout.setVerticalGroup(
            general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(general_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_jButton)
                    .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jLabel)
                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(general_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(default_RButton)
                    .addComponent(Advanced_Options_RButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        name_jTextField.getAccessibleContext().setAccessibleDescription("");
        default_RButton.getAccessibleContext().setAccessibleDescription("");
        Advanced_Options_RButton.getAccessibleContext().setAccessibleDescription("");

        EMBOSS_est2genomeEditors2.addTab("EMBOSS_est2genomeEditors", general_jPanel1);

        close_jButton.setForeground(new java.awt.Color(0, 0, 255));
        close_jButton.setText("Close");
        close_jButton.setMaximumSize(new java.awt.Dimension(91, 29));
        close_jButton.setMinimumSize(new java.awt.Dimension(91, 29));
        close_jButton.setName("close_jButton"); // NOI18N
        close_jButton.setPreferredSize(new java.awt.Dimension(91, 29));
        close_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_jButton_ActionPerformed(evt);
            }
        });

        how_jButton.setForeground(new java.awt.Color(255, 0, 255));
        how_jButton.setText("?");
        how_jButton.setMaximumSize(new java.awt.Dimension(51, 29));
        how_jButton.setMinimumSize(new java.awt.Dimension(51, 29));
        how_jButton.setName("how_jButton"); // NOI18N
        how_jButton.setPreferredSize(new java.awt.Dimension(51, 29));
        how_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how_jButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(docker_jButton)
                .addGap(18, 18, 18)
                .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(EMBOSS_est2genomeEditors2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docker_jButton)
                    .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EMBOSS_est2genomeEditors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        docker_jButton.getAccessibleContext().setAccessibleDescription("Access to the docker editor");
        EMBOSS_est2genomeEditors2.getAccessibleContext().setAccessibleName("EMBOSS_est2genomeEditors");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMBOSS_est2genomeEditors2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_EMBOSS_est2genomeEditors2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_EMBOSS_est2genomeEditors2ComponentShown
    
    private void docker_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docker_jButton_ActionPerformed
        // TODO add your handling code here:
        dockerEditor dock = new dockerEditor(this.frame, false, properties);
        dock.setVisible(true);
    }//GEN-LAST:event_docker_jButton_ActionPerformed
    
    private void name_jTextField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_jTextField_ActionPerformed
        // TODO add your handling code here:
        properties.put("Name", name_jTextField.getText());
    }//GEN-LAST:event_name_jTextField_ActionPerformed
    

    private void default_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,default_RButton,null);
        if (properties.isSet(Advanced_Options_RButton.getName())){
            properties.remove(Advanced_Options_RButton.getName());
        }
        menuFields(properties);
    }//GEN-LAST:event_default_RButton_ActionPerformed

    private void Advanced_Options_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Advanced_Options_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,Advanced_Options_RButton,null);
        if (properties.isSet(default_RButton.getName())){
            properties.remove(default_RButton.getName());
        }
        menuFields(properties);
    }//GEN-LAST:event_Advanced_Options_RButton_ActionPerformed

    private void Sq_match_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_match_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_match_Box,Sq_match_Box_IntValue);
    }//GEN-LAST:event_Sq_match_Box_ActionPerformed

    private void Sq_match_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_match_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_match_Box,Sq_match_Box_IntValue);
    }//GEN-LAST:event_Sq_match_Box_IntValue_StateChanged

    private void Sq_mismatch_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_mismatch_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_mismatch_Box,Sq_mismatch_Box_IntValue);
    }//GEN-LAST:event_Sq_mismatch_Box_ActionPerformed

    private void Sq_mismatch_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_mismatch_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_mismatch_Box,Sq_mismatch_Box_IntValue);
    }//GEN-LAST:event_Sq_mismatch_Box_IntValue_StateChanged

    private void Sq_gappenalty_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_gappenalty_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_gappenalty_Box,Sq_gappenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_gappenalty_Box_ActionPerformed

    private void Sq_gappenalty_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_gappenalty_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_gappenalty_Box,Sq_gappenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_gappenalty_Box_IntValue_StateChanged

    private void Sq_intronpenalty_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_intronpenalty_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_intronpenalty_Box,Sq_intronpenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_intronpenalty_Box_ActionPerformed

    private void Sq_intronpenalty_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_intronpenalty_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_intronpenalty_Box,Sq_intronpenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_intronpenalty_Box_IntValue_StateChanged

    private void Sq_splicepenalty_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_splicepenalty_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_splicepenalty_Box,Sq_splicepenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_splicepenalty_Box_ActionPerformed

    private void Sq_splicepenalty_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_splicepenalty_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_splicepenalty_Box,Sq_splicepenalty_Box_IntValue);
    }//GEN-LAST:event_Sq_splicepenalty_Box_IntValue_StateChanged

    private void Sq_minscore_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_minscore_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_minscore_Box,Sq_minscore_Box_IntValue);
    }//GEN-LAST:event_Sq_minscore_Box_ActionPerformed

    private void Sq_minscore_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_minscore_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_minscore_Box,Sq_minscore_Box_IntValue);
    }//GEN-LAST:event_Sq_minscore_Box_IntValue_StateChanged

    private void Sq_reverse_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_reverse_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_reverse_Box,Sq_reverse_Box_BooValue);
    }//GEN-LAST:event_Sq_reverse_Box_ActionPerformed

    private void Sq_reverse_Box_BooValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_reverse_Box_BooValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_reverse_Box,Sq_reverse_Box_BooValue);
    }//GEN-LAST:event_Sq_reverse_Box_BooValue_StateChanged

    private void Sq_usesplice_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_usesplice_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_usesplice_Box,Sq_usesplice_Box_BooValue);
    }//GEN-LAST:event_Sq_usesplice_Box_ActionPerformed

    private void Sq_usesplice_Box_BooValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_usesplice_Box_BooValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_usesplice_Box,Sq_usesplice_Box_BooValue);
    }//GEN-LAST:event_Sq_usesplice_Box_BooValue_StateChanged

    private void Sq_mode_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_mode_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventComboBox(properties,Sq_mode_Box,Sq_mode_Box_List);
    }//GEN-LAST:event_Sq_mode_Box_ActionPerformed

    private void Sq_mode_Box_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_mode_Box_List_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventComboBox(properties,Sq_mode_Box,Sq_mode_Box_List);
    }//GEN-LAST:event_Sq_mode_Box_List_ActionPerformed

    private void Sq_best_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_best_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_best_Box,Sq_best_Box_BooValue);
    }//GEN-LAST:event_Sq_best_Box_ActionPerformed

    private void Sq_best_Box_BooValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_best_Box_BooValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_best_Box,Sq_best_Box_BooValue);
    }//GEN-LAST:event_Sq_best_Box_BooValue_StateChanged

    private void Sq_space_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_space_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_space_Box,Sq_space_Box_FloValue);
    }//GEN-LAST:event_Sq_space_Box_ActionPerformed

    private void Sq_space_Box_FloValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_space_Box_FloValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_space_Box,Sq_space_Box_FloValue);
    }//GEN-LAST:event_Sq_space_Box_FloValue_StateChanged

    private void Sq_shuffle_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_shuffle_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_shuffle_Box,Sq_shuffle_Box_IntValue);
    }//GEN-LAST:event_Sq_shuffle_Box_ActionPerformed

    private void Sq_shuffle_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_shuffle_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_shuffle_Box,Sq_shuffle_Box_IntValue);
    }//GEN-LAST:event_Sq_shuffle_Box_IntValue_StateChanged

    private void Sq_seed_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_seed_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_seed_Box,Sq_seed_Box_IntValue);
    }//GEN-LAST:event_Sq_seed_Box_ActionPerformed

    private void Sq_seed_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_seed_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_seed_Box,Sq_seed_Box_IntValue);
    }//GEN-LAST:event_Sq_seed_Box_IntValue_StateChanged

    private void Sq_align_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_align_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_align_Box,Sq_align_Box_BooValue);
    }//GEN-LAST:event_Sq_align_Box_ActionPerformed

    private void Sq_align_Box_BooValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_align_Box_BooValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_align_Box,Sq_align_Box_BooValue);
    }//GEN-LAST:event_Sq_align_Box_BooValue_StateChanged

    private void Sq_width_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sq_width_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_width_Box,Sq_width_Box_IntValue);
    }//GEN-LAST:event_Sq_width_Box_ActionPerformed

    private void Sq_width_Box_IntValue_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sq_width_Box_IntValue_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,Sq_width_Box,Sq_width_Box_IntValue);
    }//GEN-LAST:event_Sq_width_Box_IntValue_StateChanged

    private void close_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_jButton_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_jButton_ActionPerformed

    private void reset_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        this.setVisible(false);
    }//GEN-LAST:event_reset_jButton_ActionPerformed

    private void stop_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton_ActionPerformed

    private void run_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton_ActionPerformed
        // TODO add your handling code here:
        if (this.properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton_ActionPerformed

    private void name_jTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_jTextFieldFocusLost
        // TODO add your handling code here:
        properties.put("Name", name_jTextField.getText());
    }//GEN-LAST:event_name_jTextFieldFocusLost

    private void how_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how_jButton_ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_how_jButton_ActionPerformed

    /*******************************************************************
     * Set the configuration properties for this object
     ******************************************************************/

    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        
        // Set the program properties
        this.setProperties(properties);
        
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    /*******************************************************************
     * Sets for Properties
     ******************************************************************/

    /**
     * Set Properties
     * @param properties
     */

    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (this.properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Dicts prepare
        Util.dictsReset(listDicts,DictBoxSpinner,DictBoxTextField,DictBoxComboBox,DictRadioButtonSpinner,DictRadioButtonTextField);
        DictBoxSpinner.put(Sq_match_Box,Sq_match_Box_IntValue);
        DictBoxSpinner.put(Sq_mismatch_Box,Sq_mismatch_Box_IntValue);
        DictBoxSpinner.put(Sq_gappenalty_Box,Sq_gappenalty_Box_IntValue);
        DictBoxSpinner.put(Sq_intronpenalty_Box,Sq_intronpenalty_Box_IntValue);
        DictBoxSpinner.put(Sq_splicepenalty_Box,Sq_splicepenalty_Box_IntValue);
        DictBoxSpinner.put(Sq_minscore_Box,Sq_minscore_Box_IntValue);
        DictBoxSpinner.put(Sq_reverse_Box,Sq_reverse_Box_BooValue);
        DictBoxSpinner.put(Sq_usesplice_Box,Sq_usesplice_Box_BooValue);
        DictBoxSpinner.put(Sq_mode_Box,Sq_reverse_Box_BooValue);
        DictBoxComboBox.put(Sq_reverse_Box,Sq_mode_Box_List);
        DictBoxSpinner.put(Sq_best_Box,Sq_best_Box_BooValue);
        DictBoxSpinner.put(Sq_space_Box,Sq_space_Box_FloValue);
        DictBoxSpinner.put(Sq_shuffle_Box,Sq_shuffle_Box_IntValue);
        DictBoxSpinner.put(Sq_seed_Box,Sq_seed_Box_IntValue);
        DictBoxSpinner.put(Sq_align_Box,Sq_align_Box_BooValue);
        DictBoxSpinner.put(Sq_width_Box,Sq_width_Box_IntValue);
        // Properties Default Options
        this.defaultPgrmValues(properties);
        // Update Saved Properties => usp
        Util.updateSavedProperties(properties,listDicts,name_jTextField);
        // Set the menu
        this.menuFields(properties);
        
    }

    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }

    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    private void defaultPgrmValues(workflow_properties properties) {
        boolean b = true;
        if (!(properties.isSet(default_RButton.getName()))
        && !(properties.isSet(Advanced_Options_RButton.getName()))
        ) {
            Util.buttonEventSpinner(properties,default_RButton,null);
            default_RButton.setSelected(true);
            b = false;
        }
        
        Util.getDefaultPgrmValues(properties,b);
    }
    
    /*******************************************************************
     * Set Menu fields
     ******************************************************************/

    private void menuFields(workflow_properties properties) {
        if (properties.isSet(default_RButton.getName())) {
            default_RButton.setSelected(true);
            Util.enabled_Advanced_Options(properties,false,listDicts);
        }
        else if (properties.isSet(Advanced_Options_RButton.getName())) {
            Advanced_Options_RButton.setSelected(true);
            Util.enabled_Advanced_Options(properties,true,listDicts);
        }
    }

    /*******************************************************************
     * Save Image
     ******************************************************************/

    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Advanced_Options_RButton;
    private javax.swing.JTabbedPane EMBOSS_est2genomeEditors2;
    private javax.swing.ButtonGroup Menu_Buttons;
    private javax.swing.JCheckBox Sq_align_Box;
    private javax.swing.JSpinner Sq_align_Box_BooValue;
    private javax.swing.JCheckBox Sq_best_Box;
    private javax.swing.JSpinner Sq_best_Box_BooValue;
    private javax.swing.JCheckBox Sq_gappenalty_Box;
    private javax.swing.JSpinner Sq_gappenalty_Box_IntValue;
    private javax.swing.JCheckBox Sq_intronpenalty_Box;
    private javax.swing.JSpinner Sq_intronpenalty_Box_IntValue;
    private javax.swing.JCheckBox Sq_match_Box;
    private javax.swing.JSpinner Sq_match_Box_IntValue;
    private javax.swing.JCheckBox Sq_minscore_Box;
    private javax.swing.JSpinner Sq_minscore_Box_IntValue;
    private javax.swing.JCheckBox Sq_mismatch_Box;
    private javax.swing.JSpinner Sq_mismatch_Box_IntValue;
    private javax.swing.JCheckBox Sq_mode_Box;
    private javax.swing.JComboBox Sq_mode_Box_List;
    private javax.swing.JPanel Sq_panel;
    private javax.swing.JCheckBox Sq_reverse_Box;
    private javax.swing.JSpinner Sq_reverse_Box_BooValue;
    private javax.swing.JCheckBox Sq_seed_Box;
    private javax.swing.JSpinner Sq_seed_Box_IntValue;
    private javax.swing.JCheckBox Sq_shuffle_Box;
    private javax.swing.JSpinner Sq_shuffle_Box_IntValue;
    private javax.swing.JCheckBox Sq_space_Box;
    private javax.swing.JSpinner Sq_space_Box_FloValue;
    private javax.swing.JCheckBox Sq_splicepenalty_Box;
    private javax.swing.JSpinner Sq_splicepenalty_Box_IntValue;
    private javax.swing.JCheckBox Sq_usesplice_Box;
    private javax.swing.JSpinner Sq_usesplice_Box_BooValue;
    private javax.swing.JCheckBox Sq_width_Box;
    private javax.swing.JSpinner Sq_width_Box_IntValue;
    private javax.swing.JButton close_jButton;
    private javax.swing.JRadioButton default_RButton;
    private javax.swing.JButton docker_jButton;
    private javax.swing.JPanel general_jPanel1;
    private javax.swing.JButton how_jButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_jLabel;
    private javax.swing.JTextField name_jTextField;
    private javax.swing.JButton reset_jButton;
    private javax.swing.JButton run_jButton;
    private javax.swing.JButton stop_jButton;
    // End of variables declaration//GEN-END:variables
    }

