/*
 *  Armadillo Workflow Platform v1.0
 *  A simple pipeline system for phylogenetic analysis
 *  
 *  Copyright (C) 2009-2011  Etienne Lord, Mickael Leclercq
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package editors;


import workflows.workflow_properties;
import configuration.Config;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import editor.EditorInterface;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import program.programs;
import workflows.armadillo_workflow;
import workflows.workflow_properties_dictionnary;

/**
 * Editor of the object properties in the Main Workflow
 * Note: Only called if object doesnt have a Custum Editor
 * @author Etienne Lord
 * @since July 2009
 */
public class GblocksEditor extends javax.swing.JDialog implements EditorInterface {

    ////////////////////////////////////////////////////////////////////////////
    /// VARIABLES

    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
   
    ////////////////////////////////////////////////////////////////////////////
    /// CONSTANT

    public final String defaultNameString=" Name";

    /** Creates new form propertiesJDialog */
    public GblocksEditor(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
        //connectorinfobox=new ConnectorInfoBox(parent); //--Used to display Connector info
        //--Initialize component
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        MoltypejComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MinimumLengthOfBlock_jComboBox = new javax.swing.JComboBox();
        AllowedGap_jComboBox = new javax.swing.JComboBox();
        MinimumConserved_jComboBox = new javax.swing.JComboBox();
        MinimumFlank_jComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        MaximumNonConserved_jComboBox = new javax.swing.JComboBox();
        UseSimilarity_jCheckBox1 = new javax.swing.JCheckBox();
        ClosejButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setTitle("Properties");

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Name");

        NamejTextField.setText(" ");

        jButton4.setText("Rename");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Type of sequence");

        MoltypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nucleic Acid (DNA)", "Protein", "Codons" }));
        MoltypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoltypejComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Type :");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterion"));

        jLabel20.setText("Minimum Number Of Sequences A Conserved Position : ");

        jLabel21.setText("Minimum Number Of Sequences For A Flank Position :");

        jLabel7.setText("Minimum Length Of A Block :");

        jLabel8.setText("Allowed Gap Positions :");

        MinimumLengthOfBlock_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "2", "3", "4", "5", "10" }));
        MinimumLengthOfBlock_jComboBox.setToolTipText("Any integer equal or bigger than 2");
        MinimumLengthOfBlock_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimumLengthOfBlock_jComboBoxActionPerformed(evt);
            }
        });

        AllowedGap_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "None", "With Half", "All" }));
        AllowedGap_jComboBox.setToolTipText("default: None");
        AllowedGap_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllowedGap_jComboBoxActionPerformed(evt);
            }
        });

        MinimumConserved_jComboBox.setEditable(true);
        MinimumConserved_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "100", "50", "25", "5", "2", "1" }));
        MinimumConserved_jComboBox.setToolTipText("50% of the number of sequences + 1");
        MinimumConserved_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimumConserved_jComboBoxActionPerformed(evt);
            }
        });

        MinimumFlank_jComboBox.setEditable(true);
        MinimumFlank_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "0.05", "0.1", "0.5", "1.0", "2.0", "5.0", "7.5", "10.0" }));
        MinimumFlank_jComboBox.setToolTipText("85% of the number of sequences");
        MinimumFlank_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimumFlank_jComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Maximum Number Of Contiguous Nonconserved Positions:");

        MaximumNonConserved_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        MaximumNonConserved_jComboBox.setToolTipText("default: 8");
        MaximumNonConserved_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximumNonConserved_jComboBoxActionPerformed(evt);
            }
        });

        UseSimilarity_jCheckBox1.setSelected(true);
        UseSimilarity_jCheckBox1.setText("Use Similarity Matrices");
        UseSimilarity_jCheckBox1.setToolTipText("Use Similarity Matrices (Only for proteins)");
        UseSimilarity_jCheckBox1.setEnabled(false);
        UseSimilarity_jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseSimilarity_jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaximumNonConserved_jComboBox, 0, 0, Short.MAX_VALUE)
                            .addComponent(AllowedGap_jComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                            .addComponent(MinimumFlank_jComboBox, 0, 0, Short.MAX_VALUE)
                            .addComponent(MinimumLengthOfBlock_jComboBox, 0, 0, Short.MAX_VALUE)
                            .addComponent(MinimumConserved_jComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)))
                    .addComponent(UseSimilarity_jCheckBox1))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(MinimumConserved_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(MinimumFlank_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MaximumNonConserved_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MinimumLengthOfBlock_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AllowedGap_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UseSimilarity_jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MoltypejComboBox, 0, 429, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoltypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );

        ClosejButton.setText("<html><b>Close</b></html>");
        ClosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Run");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("Stop");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset default values");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addGap(3, 3, 3))
        );

        jTabbedPane1.addTab("Gblocks", jPanel9);

        jButton3.setText("?");
        jButton3.setToolTipText("Help / Informations");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButtonActionPerformed
        //-- 2. Close dialog
        this.setVisible(false);
}//GEN-LAST:event_ClosejButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown

}//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        properties.put("Name", this.NamejTextField.getText());
        parent_workflow.updateCurrentWorkflow(properties);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        properties.put("Status", Config.status_nothing);
        properties.killThread();
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       if(properties.isSet("ClassName")) {
           this.parent_workflow.workflow.updateDependance();
           programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
           prog.Run(properties);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MoltypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoltypejComboBoxActionPerformed
        // 0 DNA
        // 1 Protein
        // 2 Codons        
        int type=this.MoltypejComboBox.getSelectedIndex();                
        properties.put("moltype",type);
        if (type==1) {
            this.UseSimilarity_jCheckBox1.setEnabled(true);
        } else {
            this.UseSimilarity_jCheckBox1.setEnabled(false);
            properties.remove("Use_Similarity_Matrices");
        }
        
    }//GEN-LAST:event_MoltypejComboBoxActionPerformed

    private void MinimumLengthOfBlock_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimumLengthOfBlock_jComboBoxActionPerformed
        String item=(String)this.MinimumLengthOfBlock_jComboBox.getSelectedItem();
        if (item.equals("default")) {
            properties.remove("Minimum_Length_Of_A_Block");
        } else properties.put("Minimum_Length_Of_A_Block",item);
}//GEN-LAST:event_MinimumLengthOfBlock_jComboBoxActionPerformed

    private void AllowedGap_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllowedGap_jComboBoxActionPerformed
        String item=(String)this.AllowedGap_jComboBox.getSelectedItem();
        if (item.equals("default")) {
            properties.remove("Allowed_Gap_Positions");
        } else properties.put("Allowed_Gap_Positions",item);
}//GEN-LAST:event_AllowedGap_jComboBoxActionPerformed

    private void MinimumConserved_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimumConserved_jComboBoxActionPerformed
        String item=(String)this.MinimumConserved_jComboBox.getSelectedItem();
        if (item.equals("default")) {
            properties.remove("Minimum_Number_Of_Sequences_For_A_Conserved_Position");
        } else properties.put("Minimum_Number_Of_Sequences_For_A_Conserved_Position",item);
}//GEN-LAST:event_MinimumConserved_jComboBoxActionPerformed

    private void MinimumFlank_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimumFlank_jComboBoxActionPerformed
        String item=(String)this.MinimumFlank_jComboBox.getSelectedItem();
        if (item.equals("default")) {
            properties.remove("Minimum_Number_Of_Sequences_For_A_Flank_Position");
        } else properties.put("Minimum_Number_Of_Sequences_For_A_Flank_Position",item);
}//GEN-LAST:event_MinimumFlank_jComboBoxActionPerformed

    private void MaximumNonConserved_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximumNonConserved_jComboBoxActionPerformed
        String item=(String)this. MaximumNonConserved_jComboBox.getSelectedItem();
        if (item.equals("default")) {
            properties.remove("Maximum_Number_Of_Contiguous_Nonconserved_Positions");
        } else properties.put("Maximum_Number_Of_Contiguous_Nonconserved_Positions",item);
}//GEN-LAST:event_MaximumNonConserved_jComboBoxActionPerformed

    private void UseSimilarity_jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseSimilarity_jCheckBox1ActionPerformed
       if (this.UseSimilarity_jCheckBox1.isSelected()) {
           properties.remove("Use_Similarity_Matrices");
       } else {
           properties.put("Use_Similarity_Matrices", false);
       }
    }//GEN-LAST:event_UseSimilarity_jCheckBox1ActionPerformed

   
    /**
     * This set the Properties
     * @param properties
     */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
       
        this.NamejTextField.setText(properties.getName());

        if (properties.isSet("Maximum_Number_Of_Contiguous_Nonconserved_Positions")) {
           this.MaximumNonConserved_jComboBox.setSelectedItem(properties.get("Maximum_Number_Of_Contiguous_Nonconserved_Positions"));        
        } 
        
        if (properties.isSet("Minimum_Number_Of_Sequences_For_A_Conserved_Position")) {
           this.MinimumConserved_jComboBox.setSelectedItem(properties.get("Minimum_Number_Of_Sequences_For_A_Conserved_Position"));        
        } 
        //Minimum_Number_Of_Sequences_For_A_Flank_Position
        if (properties.isSet("Minimum_Number_Of_Sequences_For_A_Flank_Position")) {
           this.MinimumFlank_jComboBox.setSelectedItem(properties.get("Minimum_Number_Of_Sequences_For_A_Flank_Position"));        
        } 
        
        if (properties.isSet("Minimum_Length_Of_A_Block")) {
           this.MinimumLengthOfBlock_jComboBox.setSelectedItem(properties.get("Minimum_Length_Of_A_Block"));        
        } 
        //Allowed_Gap_Positions
        if (properties.isSet("Allowed_Gap_Positions")) {
           this.AllowedGap_jComboBox.setSelectedItem(properties.get("Allowed_Gap_Positions"));        
        } 
        if (properties.isSet("moltype")) {
           this.MoltypejComboBox.setSelectedIndex(properties.getInt("moltype"));
           if (properties.getInt("moltype")==1) {
               this.UseSimilarity_jCheckBox1.setEnabled(true);
           } else {
               this.UseSimilarity_jCheckBox1.setEnabled(false);
           }
        } else {
            properties.put("moltype", 0); //--By default set moltype to DNA (0)
        }
        if (properties.isSet("Use_Similarity_Matrices")) {
            this.UseSimilarity_jCheckBox1.setSelected(properties.getBoolean("Use_Similarity_Matrices"));           
        } else {
            this.UseSimilarity_jCheckBox1.setSelected(true);           
        }        

    }


    ///////////////////////////////////////////////////////////////////////////
    /// DISPLAY MAIN FUNCTION

    public void display(workflow_properties properties) {
        initComponents();
        setIconImage(Config.image);
        this.setProperties(properties);
         //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        // Set position 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
					(screenSize.height-d.height)/2);
        this.setProperties(properties);
         this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds()); 
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);            
        } catch (Exception ex) {
           Config.log("Unable to save "+filename+" dialog image");
        }            
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AllowedGap_jComboBox;
    private javax.swing.JButton ClosejButton;
    private javax.swing.JComboBox MaximumNonConserved_jComboBox;
    private javax.swing.JComboBox MinimumConserved_jComboBox;
    private javax.swing.JComboBox MinimumFlank_jComboBox;
    private javax.swing.JComboBox MinimumLengthOfBlock_jComboBox;
    private javax.swing.JComboBox MoltypejComboBox;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JCheckBox UseSimilarity_jCheckBox1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables



}
