/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import editor.EditorInterface;
import configuration.Util;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author Jérémy Goimard
 * 
 */
public class miRcheck_einverted_Editors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form miRchekEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public miRcheck_einverted_Editors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        miRcheck = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        reset_jButton = new javax.swing.JButton();
        stop_jButton = new javax.swing.JButton();
        run_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name_jTextField1 = new javax.swing.JTextField();
        default_options_jbutton = new javax.swing.JRadioButton();
        advanced_options_jbutton = new javax.swing.JRadioButton();
        Options_panel = new javax.swing.JTabbedPane();
        Evaluate_panel = new javax.swing.JPanel();
        C_gap_value = new javax.swing.JSpinner();
        C_thresh_value = new javax.swing.JSpinner();
        C_m_value = new javax.swing.JSpinner();
        C_mm_value = new javax.swing.JSpinner();
        C_dist_value = new javax.swing.JSpinner();
        C_win_value = new javax.swing.JSpinner();
        C_step_value = new javax.swing.JSpinner();
        C_minPct_value = new javax.swing.JSpinner();
        C_minArm_value = new javax.swing.JSpinner();
        C_thresh_box = new javax.swing.JCheckBox();
        C_m_box = new javax.swing.JCheckBox();
        C_mm_box = new javax.swing.JCheckBox();
        C_dist_box = new javax.swing.JCheckBox();
        C_win_box = new javax.swing.JCheckBox();
        C_step_box = new javax.swing.JCheckBox();
        C_minPct_box = new javax.swing.JCheckBox();
        C_minArm_box = new javax.swing.JCheckBox();
        C_gap_box = new javax.swing.JCheckBox();
        close_jButton = new javax.swing.JButton();
        docker_jButton = new javax.swing.JButton();
        how_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        miRcheck.setMinimumSize(new java.awt.Dimension(301, 505));
        miRcheck.setPreferredSize(new java.awt.Dimension(301, 505));
        miRcheck.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                miRcheckComponentShown(evt);
            }
        });

        reset_jButton.setForeground(new java.awt.Color(255, 116, 0));
        reset_jButton.setText("Reset");
        reset_jButton.setName("reset_jButton"); // NOI18N
        reset_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton_ActionPerformed(evt);
            }
        });

        stop_jButton.setForeground(new java.awt.Color(255, 0, 0));
        stop_jButton.setText("Stop");
        stop_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setName("stop_jButton"); // NOI18N
        stop_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        stop_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton_ActionPerformed(evt);
            }
        });

        run_jButton.setForeground(new java.awt.Color(0, 255, 3));
        run_jButton.setText("Run");
        run_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        run_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        run_jButton.setName("run_jButton"); // NOI18N
        run_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        run_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton_ActionPerformed(evt);
            }
        });

        jLabel1.setText("(re)Name");

        name_jTextField1.setText("miRcheck");
        name_jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_jTextField1FocusLost(evt);
            }
        });

        buttonGroup1.add(default_options_jbutton);
        default_options_jbutton.setText("default options");
        default_options_jbutton.setName("default_options_jbutton"); // NOI18N
        default_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_options_jbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(advanced_options_jbutton);
        advanced_options_jbutton.setText("advanced options");
        advanced_options_jbutton.setName("advanced_options_jbutton"); // NOI18N
        advanced_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_options_jbuttonActionPerformed(evt);
            }
        });

        Options_panel.setPreferredSize(new java.awt.Dimension(252, 355));

        C_gap_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_gap_value.setName("C_gap_value"); // NOI18N
        C_gap_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_gap_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_gap_valueStateChanged(evt);
            }
        });

        C_thresh_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_thresh_value.setName("C_thresh_value"); // NOI18N
        C_thresh_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_thresh_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_thresh_valueStateChanged(evt);
            }
        });

        C_m_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_m_value.setName("C_m_value"); // NOI18N
        C_m_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_m_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_m_valueStateChanged(evt);
            }
        });

        C_mm_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_mm_value.setName("C_mm_value"); // NOI18N
        C_mm_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_mm_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_mm_valueStateChanged(evt);
            }
        });

        C_dist_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_dist_value.setName("C_dist_value"); // NOI18N
        C_dist_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_dist_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_dist_valueStateChanged(evt);
            }
        });

        C_win_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_win_value.setName("C_win_value"); // NOI18N
        C_win_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_win_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_win_valueStateChanged(evt);
            }
        });

        C_step_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_step_value.setName("C_step_value"); // NOI18N
        C_step_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_step_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_step_valueStateChanged(evt);
            }
        });

        C_minPct_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_minPct_value.setName("C_minPct_value"); // NOI18N
        C_minPct_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_minPct_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_minPct_valueStateChanged(evt);
            }
        });

        C_minArm_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_minArm_value.setName("C_minArm_value"); // NOI18N
        C_minArm_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_minArm_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_minArm_valueStateChanged(evt);
            }
        });

        C_thresh_box.setText("thresh");
        C_thresh_box.setName("C_thresh_box"); // NOI18N
        C_thresh_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_thresh_boxActionPerformed(evt);
            }
        });

        C_m_box.setText("m");
        C_m_box.setName("C_m_box"); // NOI18N
        C_m_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_m_boxActionPerformed(evt);
            }
        });

        C_mm_box.setText("mm");
        C_mm_box.setName("C_mm_box"); // NOI18N
        C_mm_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_mm_boxActionPerformed(evt);
            }
        });

        C_dist_box.setText("dist");
        C_dist_box.setName("C_dist_box"); // NOI18N
        C_dist_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_dist_boxActionPerformed(evt);
            }
        });

        C_win_box.setText("win");
        C_win_box.setName("C_win_box"); // NOI18N
        C_win_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_win_boxActionPerformed(evt);
            }
        });

        C_step_box.setText("step");
        C_step_box.setName("C_step_box"); // NOI18N
        C_step_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_step_boxActionPerformed(evt);
            }
        });

        C_minPct_box.setText("min pct");
        C_minPct_box.setName("C_minPct_box"); // NOI18N
        C_minPct_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_minPct_boxActionPerformed(evt);
            }
        });

        C_minArm_box.setText("min arm");
        C_minArm_box.setName("C_minArm_box"); // NOI18N
        C_minArm_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_minArm_boxActionPerformed(evt);
            }
        });

        C_gap_box.setText("gap");
        C_gap_box.setName("C_gap_box"); // NOI18N
        C_gap_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_gap_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Evaluate_panelLayout = new javax.swing.GroupLayout(Evaluate_panel);
        Evaluate_panel.setLayout(Evaluate_panelLayout);
        Evaluate_panelLayout.setHorizontalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_gap_box)
                    .addComponent(C_thresh_box)
                    .addComponent(C_m_box)
                    .addComponent(C_mm_box)
                    .addComponent(C_dist_box)
                    .addComponent(C_win_box)
                    .addComponent(C_step_box)
                    .addComponent(C_minPct_box)
                    .addComponent(C_minArm_box))
                .addGap(18, 18, 18)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_m_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_thresh_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mm_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_dist_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_step_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_win_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minArm_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minPct_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_gap_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Evaluate_panelLayout.setVerticalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_gap_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_gap_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_thresh_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_thresh_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_m_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_m_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_mm_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mm_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_dist_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_dist_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_win_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_win_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_step_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_step_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_minPct_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minPct_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_minArm_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minArm_box))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Options_panel.addTab("evaluate", Evaluate_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(default_options_jbutton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(advanced_options_jbutton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reset_jButton)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(name_jTextField1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(default_options_jbutton)
                    .addComponent(advanced_options_jbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        miRcheck.addTab("miRcheck", jPanel1);

        close_jButton.setForeground(new java.awt.Color(0, 0, 255));
        close_jButton.setText("Close");
        close_jButton.setMaximumSize(new java.awt.Dimension(91, 29));
        close_jButton.setMinimumSize(new java.awt.Dimension(91, 29));
        close_jButton.setName("close_jButton"); // NOI18N
        close_jButton.setPreferredSize(new java.awt.Dimension(91, 29));
        close_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_jButton_ActionPerformed(evt);
            }
        });

        docker_jButton.setText("Docker Editor");
        docker_jButton.setName("docker_jButton"); // NOI18N
        docker_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docker_jButton_ActionPerformed(evt);
            }
        });

        how_jButton.setForeground(new java.awt.Color(255, 0, 255));
        how_jButton.setText("?");
        how_jButton.setMaximumSize(new java.awt.Dimension(51, 29));
        how_jButton.setMinimumSize(new java.awt.Dimension(51, 29));
        how_jButton.setName("how_jButton"); // NOI18N
        how_jButton.setPreferredSize(new java.awt.Dimension(51, 29));
        how_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how_jButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(docker_jButton)
                .addGap(18, 18, 18)
                .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(miRcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docker_jButton)
                    .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miRcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void miRcheckComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_miRcheckComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_miRcheckComponentShown
    
    private void C_gap_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_gap_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_gap_box,C_gap_value);
    }//GEN-LAST:event_C_gap_valueStateChanged

    private void C_m_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_m_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_m_box,C_m_value);
    }//GEN-LAST:event_C_m_valueStateChanged

    private void C_thresh_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_thresh_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_thresh_box,C_thresh_value);
    }//GEN-LAST:event_C_thresh_valueStateChanged

    private void C_mm_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_mm_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_mm_box,C_mm_value);
    }//GEN-LAST:event_C_mm_valueStateChanged

    private void C_dist_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_dist_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_dist_box,C_dist_value);
    }//GEN-LAST:event_C_dist_valueStateChanged

    private void C_win_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_win_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_win_box,C_win_value);
    }//GEN-LAST:event_C_win_valueStateChanged

    private void C_step_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_step_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_step_box,C_step_value);
    }//GEN-LAST:event_C_step_valueStateChanged

    private void C_minPct_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_minPct_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minPct_box,C_minPct_value);
    }//GEN-LAST:event_C_minPct_valueStateChanged

    private void C_minArm_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_minArm_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minArm_box,C_minArm_value);
    }//GEN-LAST:event_C_minArm_valueStateChanged
 
    private void C_thresh_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_thresh_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_thresh_box,C_thresh_value);
    }//GEN-LAST:event_C_thresh_boxActionPerformed

    private void C_m_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_m_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_m_box,C_m_value);
    }//GEN-LAST:event_C_m_boxActionPerformed

    private void C_mm_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_mm_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_mm_box,C_mm_value);
    }//GEN-LAST:event_C_mm_boxActionPerformed

    private void C_dist_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_dist_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_dist_box,C_dist_value);
    }//GEN-LAST:event_C_dist_boxActionPerformed

    private void C_win_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_win_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_win_box,C_win_value);
    }//GEN-LAST:event_C_win_boxActionPerformed

    private void C_step_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_step_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_step_box,C_step_value);
    }//GEN-LAST:event_C_step_boxActionPerformed

    private void C_minPct_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_minPct_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minPct_box,C_minPct_value);
    }//GEN-LAST:event_C_minPct_boxActionPerformed

    private void C_minArm_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_minArm_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minArm_box,C_minArm_value);
    }//GEN-LAST:event_C_minArm_boxActionPerformed

    private void C_gap_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_gap_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_gap_box,C_gap_value);
    }//GEN-LAST:event_C_gap_boxActionPerformed

    private void advanced_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,advanced_options_jbutton,null);
        if (properties.isSet(default_options_jbutton.getName())) {
            properties.remove(default_options_jbutton.getName());
        }
        menuFields();
    }//GEN-LAST:event_advanced_options_jbuttonActionPerformed

    private void default_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,default_options_jbutton,null);
        if (properties.isSet(advanced_options_jbutton.getName())) {
            properties.remove(advanced_options_jbutton.getName());
        }
        menuFields();
    }//GEN-LAST:event_default_options_jbuttonActionPerformed

    private void name_jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_jTextField1FocusLost
        // TODO add your handling code here:
        String s = name_jTextField1.getText();
        if (!s.equals("")){
            properties.put("Name", name_jTextField1.getText());
        }
    }//GEN-LAST:event_name_jTextField1FocusLost

    private void reset_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        this.setVisible(false);
    }//GEN-LAST:event_reset_jButton_ActionPerformed

    private void close_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_jButton_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_jButton_ActionPerformed

    private void stop_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton_ActionPerformed

    private void docker_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docker_jButton_ActionPerformed
        // TODO add your handling code here:
        dockerEditor dock = new dockerEditor(this.frame, false, properties);
        dock.setVisible(true);
    }//GEN-LAST:event_docker_jButton_ActionPerformed

    private void run_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton_ActionPerformed
        // TODO add your handling code here:
        if (properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton_ActionPerformed

    private void how_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how_jButton_ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_how_jButton_ActionPerformed
    
    /**
    ***************************************************************************
    * Set Properties
    ***************************************************************************
    */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues();
        // Update Saved Properties => usp
        this.updateSavedProperties();
        // Set the menu
        this.menuFields();
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }
    
    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/
    
    private void updateSavedProperties() {
        usp_valueANDtext();
        usp_boxANDbutton();
        name_jTextField1.setText(properties.getName());
    }
    
    private void usp_valueANDtext () {
        if (properties.isSet(C_step_value.getName())){
            this.C_step_value.setValue(Integer.parseInt(properties.get(C_step_value.getName())));
            this.C_step_value.setVisible(false);
        }
        if (properties.isSet(C_minArm_value.getName())){
            this.C_minArm_value.setValue(Integer.parseInt(properties.get(C_minArm_value.getName())));
            this.C_minArm_value.setVisible(false);
        }
        if (properties.isSet(C_win_value.getName())){
            this.C_win_value.setValue(Integer.parseInt(properties.get(C_win_value.getName())));
            this.C_win_value.setVisible(false);
        }
        if (properties.isSet(C_minPct_value.getName())){
            this.C_minPct_value.setValue(Integer.parseInt(properties.get(C_minPct_value.getName())));
            this.C_minPct_value.setVisible(false);
        }
        if (properties.isSet(C_mm_value.getName())){
            this.C_mm_value.setValue(Integer.parseInt(properties.get(C_mm_value.getName())));
            this.C_mm_value.setVisible(false);
        }
        if (properties.isSet(C_m_value.getName())){
            this.C_m_value.setValue(Integer.parseInt(properties.get(C_m_value.getName())));
            this.C_m_value.setVisible(false);
        }
        if (properties.isSet(C_dist_value.getName())){
            this.C_dist_value.setValue(Integer.parseInt(properties.get(C_dist_value.getName())));
            this.C_dist_value.setVisible(false);
        }
        if (properties.isSet(C_thresh_value.getName())){
            this.C_thresh_value.setValue(Integer.parseInt(properties.get(C_thresh_value.getName())));
            this.C_thresh_value.setVisible(false);
        }
        if (properties.isSet(C_gap_value.getName())){
            this.C_gap_value.setValue(Integer.parseInt(properties.get(C_gap_value.getName())));
            this.C_gap_value.setVisible(false);
        }
    }
    
    private void usp_boxANDbutton () {
        if (properties.isSet(C_step_box.getName())){
            this.C_step_box.setSelected(true);
            this.C_step_value.setEnabled(true);
        }
        if (properties.isSet(C_minArm_box.getName())){
            this.C_minArm_box.setSelected(true);
            this.C_minArm_value.setEnabled(true);
        }
        if (properties.isSet(C_win_box.getName())){
            this.C_win_box.setSelected(true);
            this.C_win_value.setEnabled(true);
        }
        if (properties.isSet(C_minPct_box.getName())){
            this.C_minPct_box.setSelected(true);
            this.C_minPct_value.setEnabled(true);
        }
        if (properties.isSet(C_mm_box.getName())){
            this.C_mm_box.setSelected(true);
            this.C_mm_value.setEnabled(true);
        }
        if (properties.isSet(C_m_box.getName())){
            this.C_m_box.setSelected(true);
            this.C_m_value.setEnabled(true);
        }
        if (properties.isSet(C_dist_box.getName())){
            this.C_dist_box.setSelected(true);
            this.C_dist_value.setEnabled(true);
        }
        if (properties.isSet(C_thresh_box.getName())){
            this.C_thresh_box.setSelected(true);
            this.C_thresh_value.setEnabled(true);
        }
        if (properties.isSet(C_gap_box.getName())){
            this.C_gap_box.setSelected(true);
            this.C_gap_value.setEnabled(true);
        }
    }
    
    /*******************************************************************
     * Set Menu fields
     ******************************************************************/
    
    private void menuFields() {
        if (properties.isSet(default_options_jbutton.getName())) {
            default_options_jbutton.setSelected(true);
            enabled_Advanced_Options (false);
        }
        else if (properties.isSet(advanced_options_jbutton.getName())) {
            advanced_options_jbutton.setSelected(true);
            enabled_Advanced_Options (true);
        }
    }

    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabled_Advanced_Options (boolean e) {
        this.C_step_box.setEnabled(e);
        if (properties.isSet(C_step_box.getName()) && e==true) {
            this.C_step_value.setEnabled(true);
        } else {
            this.C_step_value.setEnabled(false);
        }
        
        this.C_minArm_box.setEnabled(e);
        if (properties.isSet(C_minArm_box.getName()) && e==true) {
            this.C_minArm_value.setEnabled(true);
        } else {
            this.C_minArm_value.setEnabled(false);
        }
        
        this.C_win_box.setEnabled(e);
        if (properties.isSet(C_win_box.getName()) && e==true) {
            this.C_win_value.setEnabled(true);
        } else {
            this.C_win_value.setEnabled(false);
        }
        
        this.C_minPct_box.setEnabled(e);
        if (properties.isSet(C_minPct_box.getName()) && e==true) {
            this.C_minPct_value.setEnabled(true);
        } else {
            this.C_minPct_value.setEnabled(false);
        }
        
        this.C_mm_box.setEnabled(e);
        if (properties.isSet(C_mm_box.getName()) && e==true) {
            this.C_mm_value.setEnabled(true);
        } else {
            this.C_mm_value.setEnabled(false);
        }
        
        this.C_m_box.setEnabled(e);
        if (properties.isSet(C_m_box.getName()) && e==true) {
            this.C_m_value.setEnabled(true);
        } else {
            this.C_m_value.setEnabled(false);
        }
        
        this.C_dist_box.setEnabled(e);
        if (properties.isSet(C_dist_box.getName()) && e==true) {
            this.C_dist_value.setEnabled(true);
        } else {
            this.C_dist_value.setEnabled(false);
        }
        
        this.C_thresh_box.setEnabled(e);
        if (properties.isSet(C_thresh_box.getName()) && e==true) {
            this.C_thresh_value.setEnabled(true);
        } else {
            this.C_thresh_value.setEnabled(false);
        }
        
        this.C_gap_box.setEnabled(e);
        if (properties.isSet(C_gap_box.getName()) && e==true) {
            this.C_gap_value.setEnabled(true);
        } else {
            this.C_gap_value.setEnabled(false);
        }
    }
    
    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    private void defaultPgrmValues() {
        boolean b = true;
        if (!(properties.isSet(default_options_jbutton.getName()))
        && !(properties.isSet(advanced_options_jbutton.getName()))
        ) {
            b = false;
        }
        
        Util.getDefaultPgrmValues(properties,b);
    }
    
    /**
     * Set the configuration properties for this object
     */
    
    
    
    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setProperties(properties);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    @Override
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C_dist_box;
    private javax.swing.JSpinner C_dist_value;
    private javax.swing.JCheckBox C_gap_box;
    private javax.swing.JSpinner C_gap_value;
    private javax.swing.JCheckBox C_m_box;
    private javax.swing.JSpinner C_m_value;
    private javax.swing.JCheckBox C_minArm_box;
    private javax.swing.JSpinner C_minArm_value;
    private javax.swing.JCheckBox C_minPct_box;
    private javax.swing.JSpinner C_minPct_value;
    private javax.swing.JCheckBox C_mm_box;
    private javax.swing.JSpinner C_mm_value;
    private javax.swing.JCheckBox C_step_box;
    private javax.swing.JSpinner C_step_value;
    private javax.swing.JCheckBox C_thresh_box;
    private javax.swing.JSpinner C_thresh_value;
    private javax.swing.JCheckBox C_win_box;
    private javax.swing.JSpinner C_win_value;
    private javax.swing.JPanel Evaluate_panel;
    private javax.swing.JTabbedPane Options_panel;
    private javax.swing.JRadioButton advanced_options_jbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close_jButton;
    private javax.swing.JRadioButton default_options_jbutton;
    private javax.swing.JButton docker_jButton;
    private javax.swing.JButton how_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane miRcheck;
    private javax.swing.JTextField name_jTextField1;
    private javax.swing.JButton reset_jButton;
    private javax.swing.JButton run_jButton;
    private javax.swing.JButton stop_jButton;
    // End of variables declaration//GEN-END:variables
}
