/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import editor.EditorInterface;
import configuration.Util;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author Jérémy Goimard
 * 
 */
public class miRcheck_evaluate_miRNA_candidates_Editors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form miRchekEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public miRcheck_evaluate_miRNA_candidates_Editors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        miRcheck = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        reset_jButton = new javax.swing.JButton();
        stop_jButton = new javax.swing.JButton();
        run_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name_jTextField1 = new javax.swing.JTextField();
        default_options_jbutton = new javax.swing.JRadioButton();
        advanced_options_jbutton = new javax.swing.JRadioButton();
        Options_panel = new javax.swing.JTabbedPane();
        Evaluate_panel = new javax.swing.JPanel();
        C_unpair_value = new javax.swing.JSpinner();
        C_starUnpair_value = new javax.swing.JSpinner();
        C_sizeDiff_value = new javax.swing.JSpinner();
        C_mirBulge_value = new javax.swing.JSpinner();
        C_starBulge_value = new javax.swing.JSpinner();
        C_fbackMin_value = new javax.swing.JSpinner();
        C_ass_value = new javax.swing.JSpinner();
        C_minUnpair_value = new javax.swing.JSpinner();
        C_bpExt_value = new javax.swing.JSpinner();
        C_starUnpair_box = new javax.swing.JCheckBox();
        C_sizeDiff_box = new javax.swing.JCheckBox();
        C_mirBulge_box = new javax.swing.JCheckBox();
        C_starBulge_box = new javax.swing.JCheckBox();
        C_fbackMin_box = new javax.swing.JCheckBox();
        C_ass_box = new javax.swing.JCheckBox();
        C_minUnpair_box = new javax.swing.JCheckBox();
        C_bpExt_box = new javax.swing.JCheckBox();
        C_unpair_box = new javax.swing.JCheckBox();
        close_jButton = new javax.swing.JButton();
        how_jButton = new javax.swing.JButton();
        docker_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(339, 735));

        miRcheck.setMinimumSize(new java.awt.Dimension(336, 516));
        miRcheck.setPreferredSize(new java.awt.Dimension(336, 516));
        miRcheck.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                miRcheckComponentShown(evt);
            }
        });

        reset_jButton.setForeground(new java.awt.Color(255, 116, 0));
        reset_jButton.setText("Reset");
        reset_jButton.setName("reset_jButton"); // NOI18N
        reset_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton_ActionPerformed(evt);
            }
        });

        stop_jButton.setForeground(new java.awt.Color(255, 0, 0));
        stop_jButton.setText("Stop");
        stop_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        stop_jButton.setName("stop_jButton"); // NOI18N
        stop_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        stop_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton_ActionPerformed(evt);
            }
        });

        run_jButton.setForeground(new java.awt.Color(0, 255, 3));
        run_jButton.setText("Run");
        run_jButton.setMaximumSize(new java.awt.Dimension(71, 29));
        run_jButton.setMinimumSize(new java.awt.Dimension(71, 29));
        run_jButton.setName("run_jButton"); // NOI18N
        run_jButton.setPreferredSize(new java.awt.Dimension(71, 29));
        run_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        name_jTextField1.setText("miRcheck evaluate miRNA candidates");
        name_jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_jTextField1FocusLost(evt);
            }
        });

        buttonGroup1.add(default_options_jbutton);
        default_options_jbutton.setText("default options");
        default_options_jbutton.setName("default_options_jbutton"); // NOI18N
        default_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_options_jbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(advanced_options_jbutton);
        advanced_options_jbutton.setText("advanced options");
        advanced_options_jbutton.setName("advanced_options_jbutton"); // NOI18N
        advanced_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_options_jbuttonActionPerformed(evt);
            }
        });

        Options_panel.setPreferredSize(new java.awt.Dimension(341, 413));

        C_unpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_unpair_value.setName("E_minUnpair_value"); // NOI18N
        C_unpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_unpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_unpair_valueStateChanged(evt);
            }
        });

        C_starUnpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_starUnpair_value.setName("C_starUnpair_value"); // NOI18N
        C_starUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_starUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_starUnpair_valueStateChanged(evt);
            }
        });

        C_sizeDiff_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_sizeDiff_value.setName("C_sizeDiff_value"); // NOI18N
        C_sizeDiff_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_sizeDiff_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_sizeDiff_valueStateChanged(evt);
            }
        });

        C_mirBulge_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_mirBulge_value.setName("C_mirBulge_value"); // NOI18N
        C_mirBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_mirBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_mirBulge_valueStateChanged(evt);
            }
        });

        C_starBulge_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_starBulge_value.setName("C_starBulge_value"); // NOI18N
        C_starBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_starBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_starBulge_valueStateChanged(evt);
            }
        });

        C_fbackMin_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_fbackMin_value.setName("C_fbackMin_value"); // NOI18N
        C_fbackMin_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_fbackMin_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_fbackMin_valueStateChanged(evt);
            }
        });

        C_ass_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_ass_value.setName("C_ass_value"); // NOI18N
        C_ass_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_ass_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_ass_valueStateChanged(evt);
            }
        });

        C_minUnpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_minUnpair_value.setName("C_minUnpair_value"); // NOI18N
        C_minUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_minUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_minUnpair_valueStateChanged(evt);
            }
        });

        C_bpExt_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_bpExt_value.setName("C_bpExt_value"); // NOI18N
        C_bpExt_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_bpExt_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_bpExt_valueStateChanged(evt);
            }
        });

        C_starUnpair_box.setText("star_unpair");
        C_starUnpair_box.setName("C_starUnpair_box"); // NOI18N
        C_starUnpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_starUnpair_boxActionPerformed(evt);
            }
        });

        C_sizeDiff_box.setText("size_diff");
        C_sizeDiff_box.setName("C_sizeDiff_box"); // NOI18N
        C_sizeDiff_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_sizeDiff_boxActionPerformed(evt);
            }
        });

        C_mirBulge_box.setText("mir_bulge");
        C_mirBulge_box.setName("C_mirBulge_box"); // NOI18N
        C_mirBulge_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_mirBulge_boxActionPerformed(evt);
            }
        });

        C_starBulge_box.setText("star_bulge");
        C_starBulge_box.setName("C_starBulge_box"); // NOI18N
        C_starBulge_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_starBulge_boxActionPerformed(evt);
            }
        });

        C_fbackMin_box.setText("fback_min");
        C_fbackMin_box.setName("C_fbackMin_box"); // NOI18N
        C_fbackMin_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_fbackMin_boxActionPerformed(evt);
            }
        });

        C_ass_box.setText("ass");
        C_ass_box.setName("C_ass_box"); // NOI18N
        C_ass_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ass_boxActionPerformed(evt);
            }
        });

        C_minUnpair_box.setText("min_unpair");
        C_minUnpair_box.setName("C_minUnpair_box"); // NOI18N
        C_minUnpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_minUnpair_boxActionPerformed(evt);
            }
        });

        C_bpExt_box.setText("bp_ext");
        C_bpExt_box.setName("C_bpExt_box"); // NOI18N
        C_bpExt_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_bpExt_boxActionPerformed(evt);
            }
        });

        C_unpair_box.setText("unpair");
        C_unpair_box.setName("C_unpair_box"); // NOI18N
        C_unpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_unpair_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Evaluate_panelLayout = new javax.swing.GroupLayout(Evaluate_panel);
        Evaluate_panel.setLayout(Evaluate_panelLayout);
        Evaluate_panelLayout.setHorizontalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_unpair_box)
                    .addComponent(C_starUnpair_box)
                    .addComponent(C_sizeDiff_box)
                    .addComponent(C_mirBulge_box)
                    .addComponent(C_starBulge_box)
                    .addComponent(C_fbackMin_box)
                    .addComponent(C_ass_box)
                    .addComponent(C_minUnpair_box)
                    .addComponent(C_bpExt_box))
                .addGap(18, 18, 18)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Evaluate_panelLayout.setVerticalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_unpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starUnpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_sizeDiff_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mirBulge_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starBulge_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_fbackMin_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_ass_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minUnpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_bpExt_box))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Options_panel.addTab("advanced options", Evaluate_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reset_jButton)
                                .addGap(32, 32, 32)
                                .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(default_options_jbutton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(advanced_options_jbutton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_jButton)
                    .addComponent(run_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(default_options_jbutton)
                    .addComponent(advanced_options_jbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        miRcheck.addTab("miRcheck evaluate miRNA candidates", jPanel1);

        close_jButton.setForeground(new java.awt.Color(0, 0, 255));
        close_jButton.setText("Close");
        close_jButton.setMaximumSize(new java.awt.Dimension(91, 29));
        close_jButton.setMinimumSize(new java.awt.Dimension(91, 29));
        close_jButton.setName("close_jButton"); // NOI18N
        close_jButton.setPreferredSize(new java.awt.Dimension(91, 29));
        close_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_jButton_ActionPerformed(evt);
            }
        });

        how_jButton.setForeground(new java.awt.Color(255, 0, 255));
        how_jButton.setText("?");
        how_jButton.setMaximumSize(new java.awt.Dimension(51, 29));
        how_jButton.setMinimumSize(new java.awt.Dimension(51, 29));
        how_jButton.setName("how_jButton"); // NOI18N
        how_jButton.setPreferredSize(new java.awt.Dimension(51, 29));
        how_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how_jButton_ActionPerformed(evt);
            }
        });

        docker_jButton.setText("Docker Editor");
        docker_jButton.setName("docker_jButton"); // NOI18N
        docker_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docker_jButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(docker_jButton)
                .addGap(18, 18, 18)
                .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(miRcheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(how_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docker_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miRcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void miRcheckComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_miRcheckComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_miRcheckComponentShown
    
    private void C_unpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_unpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_unpair_valueStateChanged

    private void C_sizeDiff_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_sizeDiff_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_sizeDiff_box,C_sizeDiff_value);
    }//GEN-LAST:event_C_sizeDiff_valueStateChanged

    private void C_starUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_starUnpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_starUnpair_box,C_starUnpair_value);
    }//GEN-LAST:event_C_starUnpair_valueStateChanged

    private void C_mirBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_mirBulge_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_mirBulge_box,C_mirBulge_value);
    }//GEN-LAST:event_C_mirBulge_valueStateChanged

    private void C_starBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_starBulge_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_starBulge_box,C_starBulge_value);
    }//GEN-LAST:event_C_starBulge_valueStateChanged

    private void C_fbackMin_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_fbackMin_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_fbackMin_box,C_fbackMin_value);
    }//GEN-LAST:event_C_fbackMin_valueStateChanged

    private void C_ass_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_ass_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_ass_box,C_ass_value);
    }//GEN-LAST:event_C_ass_valueStateChanged

    private void C_minUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_minUnpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minUnpair_box,C_minUnpair_value);
    }//GEN-LAST:event_C_minUnpair_valueStateChanged

    private void C_bpExt_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_bpExt_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_bpExt_box,C_bpExt_value);
    }//GEN-LAST:event_C_bpExt_valueStateChanged
 
    private void C_starUnpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_starUnpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_starUnpair_boxActionPerformed

    private void C_sizeDiff_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_sizeDiff_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_sizeDiff_boxActionPerformed

    private void C_mirBulge_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_mirBulge_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_mirBulge_boxActionPerformed

    private void C_starBulge_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_starBulge_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_starBulge_boxActionPerformed

    private void C_fbackMin_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_fbackMin_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_fbackMin_boxActionPerformed

    private void C_ass_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ass_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_ass_boxActionPerformed

    private void C_minUnpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_minUnpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_minUnpair_boxActionPerformed

    private void C_bpExt_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_bpExt_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_bpExt_boxActionPerformed

    private void C_unpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_unpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_unpair_boxActionPerformed

    private void advanced_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,advanced_options_jbutton,null);
        if (properties.isSet(default_options_jbutton.getName())) {
            properties.remove(default_options_jbutton.getName());
            default_options_jbutton.setSelected(false);
        }
        menuFields();
    }//GEN-LAST:event_advanced_options_jbuttonActionPerformed

    private void default_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,default_options_jbutton,null);
        if (properties.isSet(advanced_options_jbutton.getName())) {
            properties.remove(advanced_options_jbutton.getName());
            advanced_options_jbutton.setSelected(false);
        }
        menuFields();
    }//GEN-LAST:event_default_options_jbuttonActionPerformed

    private void name_jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_jTextField1FocusLost
        // TODO add your handling code here:
        String s = name_jTextField1.getText();
        if (!s.equals("")){
            properties.put("Name", name_jTextField1.getText());
        }
    }//GEN-LAST:event_name_jTextField1FocusLost

    private void reset_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        this.setVisible(false);
    }//GEN-LAST:event_reset_jButton_ActionPerformed

    private void close_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_jButton_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_jButton_ActionPerformed

    private void stop_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton_ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton_ActionPerformed

    private void docker_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docker_jButton_ActionPerformed
        // TODO add your handling code here:
        dockerEditor dock = new dockerEditor(this.frame, false, properties);
        dock.setVisible(true);
    }//GEN-LAST:event_docker_jButton_ActionPerformed

    private void run_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton_ActionPerformed
        // TODO add your handling code here:
        if (properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton_ActionPerformed

    private void how_jButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how_jButton_ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_how_jButton_ActionPerformed
    
    /**
    ***************************************************************************
    * Set Properties
    ***************************************************************************
    */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues();
        // Update Saved Properties => usp
        this.updateSavedProperties();
        // Set the menu
        this.menuFields();
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }
    
    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/
    
    private void updateSavedProperties() {
        usp_valueANDtext();
        usp_boxANDbutton();
        name_jTextField1.setText(properties.getName());
    }
    
    private void usp_valueANDtext() {
        if (properties.isSet(C_ass_value.getName())){
            this.C_ass_value.setValue(Integer.parseInt(properties.get(C_ass_value.getName())));
            this.C_ass_value.setVisible(false);
        }
        if (properties.isSet(C_bpExt_value.getName())){
            this.C_bpExt_value.setValue(Integer.parseInt(properties.get(C_bpExt_value.getName())));
            this.C_bpExt_value.setVisible(false);
        }
        if (properties.isSet(C_fbackMin_value.getName())){
            this.C_fbackMin_value.setValue(Integer.parseInt(properties.get(C_fbackMin_value.getName())));
            this.C_fbackMin_value.setVisible(false);
        }
        if (properties.isSet(C_minUnpair_value.getName())){
            this.C_minUnpair_value.setValue(Integer.parseInt(properties.get(C_minUnpair_value.getName())));
            this.C_minUnpair_value.setVisible(false);
        }
        if (properties.isSet(C_mirBulge_value.getName())){
            this.C_mirBulge_value.setValue(Integer.parseInt(properties.get(C_mirBulge_value.getName())));
            this.C_mirBulge_value.setVisible(false);
        }
        if (properties.isSet(C_sizeDiff_value.getName())){
            this.C_sizeDiff_value.setValue(Integer.parseInt(properties.get(C_sizeDiff_value.getName())));
            this.C_sizeDiff_value.setVisible(false);
        }
        if (properties.isSet(C_starBulge_value.getName())){
            this.C_starBulge_value.setValue(Integer.parseInt(properties.get(C_starBulge_value.getName())));
            this.C_starBulge_value.setVisible(false);
        }
        if (properties.isSet(C_starUnpair_value.getName())){
            this.C_starUnpair_value.setValue(Integer.parseInt(properties.get(C_starUnpair_value.getName())));
            this.C_starUnpair_value.setVisible(false);
        }
        if (properties.isSet(C_unpair_value.getName())){
            this.C_unpair_value.setValue(Integer.parseInt(properties.get(C_unpair_value.getName())));
            this.C_unpair_value.setVisible(false);
        }
    }
    
    private void usp_boxANDbutton() {
        if (properties.isSet(C_ass_box.getName())){
            this.C_ass_box.setSelected(true);
            this.C_ass_value.setEnabled(true);
        }
        if (properties.isSet(C_bpExt_box.getName())){
            this.C_bpExt_box.setSelected(true);
            this.C_bpExt_value.setEnabled(true);
        }
        if (properties.isSet(C_fbackMin_box.getName())){
            this.C_fbackMin_box.setSelected(true);
            this.C_fbackMin_value.setEnabled(true);
        }
        if (properties.isSet(C_minUnpair_box.getName())){
            this.C_minUnpair_box.setSelected(true);
            this.C_minUnpair_value.setEnabled(true);
        }
        if (properties.isSet(C_mirBulge_box.getName())){
            this.C_mirBulge_box.setSelected(true);
            this.C_mirBulge_value.setEnabled(true);
        }
        if (properties.isSet(C_sizeDiff_box.getName())){
            this.C_sizeDiff_box.setSelected(true);
            this.C_sizeDiff_value.setEnabled(true);
        }
        if (properties.isSet(C_starBulge_box.getName())){
            this.C_starBulge_box.setSelected(true);
            this.C_starBulge_value.setEnabled(true);
        }
        if (properties.isSet(C_starUnpair_box.getName())){
            this.C_starUnpair_box.setSelected(true);
            this.C_starUnpair_value.setEnabled(true);
        }
        if (properties.isSet(C_unpair_box.getName())){
            this.C_unpair_box.setSelected(true);
            this.C_unpair_value.setEnabled(true);
        }
    }
    
    /*******************************************************************
     * Set Menu fields
     ******************************************************************/
    
    private void menuFields() {
        if (properties.isSet(default_options_jbutton.getName())) {
            default_options_jbutton.setSelected(true);
            enabled_Advanced_Options (false);
        }
        else if (properties.isSet(advanced_options_jbutton.getName())) {
            advanced_options_jbutton.setSelected(true);
            enabled_Advanced_Options (true);
        }
    }

    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabled_Advanced_Options (boolean e) {
        this.C_ass_box.setEnabled(e);
        if (properties.isSet(C_ass_box.getName()) && e==true) {
            this.C_ass_value.setEnabled(true);
        } else {
            this.C_ass_value.setEnabled(false);
        }
        
        this.C_bpExt_box.setEnabled(e);
        if (properties.isSet(C_bpExt_box.getName()) && e==true) {
            this.C_bpExt_value.setEnabled(true);
        } else {
            this.C_bpExt_value.setEnabled(false);
        }
        
        this.C_fbackMin_box.setEnabled(e);
        if (properties.isSet(C_fbackMin_box.getName()) && e==true) {
            this.C_fbackMin_value.setEnabled(true);
        } else {
            this.C_fbackMin_value.setEnabled(false);
        }
        
        this.C_minUnpair_box.setEnabled(e);
        if (properties.isSet(C_minUnpair_box.getName()) && e==true) {
            this.C_minUnpair_value.setEnabled(true);
        } else {
            this.C_minUnpair_value.setEnabled(false);
        }
        
        this.C_mirBulge_box.setEnabled(e);
        if (properties.isSet(C_mirBulge_box.getName()) && e==true) {
            this.C_mirBulge_value.setEnabled(true);
        } else {
            this.C_mirBulge_value.setEnabled(false);
        }
        
        this.C_sizeDiff_box.setEnabled(e);
        if (properties.isSet(C_sizeDiff_box.getName()) && e==true) {
            this.C_sizeDiff_value.setEnabled(true);
        } else {
            this.C_sizeDiff_value.setEnabled(false);
        }
        
        this.C_starBulge_box.setEnabled(e);
        if (properties.isSet(C_starBulge_box.getName()) && e==true) {
            this.C_starBulge_value.setEnabled(true);
        } else {
            this.C_starBulge_value.setEnabled(false);
        }
        
        this.C_starUnpair_box.setEnabled(e);
        if (properties.isSet(C_starUnpair_box.getName()) && e==true) {
            this.C_starUnpair_value.setEnabled(true);
        } else {
            this.C_starUnpair_value.setEnabled(false);
        }
        
        this.C_unpair_box.setEnabled(e);
        if (properties.isSet(C_unpair_box.getName()) && e==true) {
            this.C_unpair_value.setEnabled(true);
        } else {
            this.C_unpair_value.setEnabled(false);
        }
    }
    
    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    private void defaultPgrmValues() {
        boolean b = true;
        if (!(properties.isSet(default_options_jbutton.getName()))
        && !(properties.isSet(advanced_options_jbutton.getName()))
        ) {
            b = false;
        }
        
        Util.getDefaultPgrmValues(properties,b);
    }
    
    /**
     * Set the configuration properties for this object
     */
    
    
    
    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setProperties(properties);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    @Override
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C_ass_box;
    private javax.swing.JSpinner C_ass_value;
    private javax.swing.JCheckBox C_bpExt_box;
    private javax.swing.JSpinner C_bpExt_value;
    private javax.swing.JCheckBox C_fbackMin_box;
    private javax.swing.JSpinner C_fbackMin_value;
    private javax.swing.JCheckBox C_minUnpair_box;
    private javax.swing.JSpinner C_minUnpair_value;
    private javax.swing.JCheckBox C_mirBulge_box;
    private javax.swing.JSpinner C_mirBulge_value;
    private javax.swing.JCheckBox C_sizeDiff_box;
    private javax.swing.JSpinner C_sizeDiff_value;
    private javax.swing.JCheckBox C_starBulge_box;
    private javax.swing.JSpinner C_starBulge_value;
    private javax.swing.JCheckBox C_starUnpair_box;
    private javax.swing.JSpinner C_starUnpair_value;
    private javax.swing.JCheckBox C_unpair_box;
    private javax.swing.JSpinner C_unpair_value;
    private javax.swing.JPanel Evaluate_panel;
    private javax.swing.JTabbedPane Options_panel;
    private javax.swing.JRadioButton advanced_options_jbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close_jButton;
    private javax.swing.JRadioButton default_options_jbutton;
    private javax.swing.JButton docker_jButton;
    private javax.swing.JButton how_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane miRcheck;
    private javax.swing.JTextField name_jTextField1;
    private javax.swing.JButton reset_jButton;
    private javax.swing.JButton run_jButton;
    private javax.swing.JButton stop_jButton;
    // End of variables declaration//GEN-END:variables
}
