/**
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import configuration.Util;
import editor.EditorInterface;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author Jérémy Goimard
 */

public class test_Pgrm_michEditors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form test_Pgrm_michEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected = "";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow  parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public test_Pgrm_michEditors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        how_jButton1 = new javax.swing.JButton();            //Basic Panel
        test_Pgrm_michEditor = new javax.swing.JTabbedPane(); //Basic Panel
        general_jPanel1 = new javax.swing.JPanel();          //Basic Panel
        rename_jButton2 = new javax.swing.JButton();         //Basic Panel
        name_jTextField1 = new javax.swing.JTextField();     //Basic Panel
        name_jLabel1 = new javax.swing.JLabel();             //Basic Panel
        reset_jButton3 = new javax.swing.JButton();          //Basic Panel
        stop_jButton4 = new javax.swing.JButton();           //Basic Panel
        run_jButton5 = new javax.swing.JButton();            //Basic Panel
        close_jButton6 = new javax.swing.JButton();          //Basic Panel
        TM_prout_RButton = new javax.swing.JRadioButton();
        TM_looc_box = new javax.swing.JCheckBox();
        TM_looc_value = new javax.swing.JSpinner();
        TM_tnaihc_box = new javax.swing.JCheckBox();
        TM_tnaihc_text = new javax.swing.JTextField();
        TM_ST_coolTop_box = new javax.swing.JCheckBox();
        TM_ST_coolTop_value = new javax.swing.JSpinner();
        TM_ST_chiant6576_box = new javax.swing.JCheckBox();
        TM_ST_chiant6576_text = new javax.swing.JTextField();
        TM_ST_bravo87_box = new javax.swing.JCheckBox();
        TM_STTo_cool2_RButton = new javax.swing.JRadioButton();
        TM_STTo_cool2_value = new javax.swing.JSpinner();
        TM_STTo_cool32_box = new javax.swing.JCheckBox();
        TM_STTo_cool32_value = new javax.swing.JSpinner();
        TM_STTo_chiant2_RButton = new javax.swing.JRadioButton();
        TM_STTo_chiant2_text = new javax.swing.JTextField();
        TM_STTo_bravo2_box = new javax.swing.JCheckBox();
        TiMe_looc_box = new javax.swing.JCheckBox();
        TiMe_looc_value = new javax.swing.JSpinner();
        TiMe_tnaihc_box = new javax.swing.JCheckBox();
        TiMe_tnaihc_text = new javax.swing.JTextField();
        TiMe_ovarb_box = new javax.swing.JCheckBox();
        TiMe_q_box = new javax.swing.JCheckBox();
        TM_ST_panel = new javax.swing.JPanel();
        TiMe_panel = new javax.swing.JPanel();
        TM_STTo_panel = new javax.swing.JPanel();
        TM_AT_panel = new javax.swing.JPanel();
        TM_panel = new javax.swing.JPanel();
        TM_tabpanel = new javax.swing.JTabbedPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


            how_jButton1.setText("?");
            how_jButton1.setName("how_jButton1"); // NOI18N
            how_jButton1.getAccessibleContext().setAccessibleDescription("");
            how_jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    how_jButton1_ActionPerformed(evt);
                }
            });


            name_jTextField1.setText("test_Pgrm_michEditor");
            name_jTextField1.setName("name_jTextField1"); // NOI18N
            name_jTextField1.getAccessibleContext().setAccessibleDescription("");
            name_jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    name_jTextField1_ActionPerformed(evt);
                }
            });


            rename_jButton2.setText("Rename");
            rename_jButton2.setName("rename_jButton2"); // NOI18N
            rename_jButton2.getAccessibleContext().setAccessibleDescription("Rename the box");
            rename_jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rename_jButton2_ActionPerformed(evt);
                }
            });


            reset_jButton3.setText("Reset");
            reset_jButton3.setName("reset_jButton3"); // NOI18N
            reset_jButton3.getAccessibleContext().setAccessibleDescription("Reset default value");
            reset_jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    reset_jButton3_ActionPerformed(evt);
                }
            });


            stop_jButton4.setText("Stop");
            stop_jButton4.setName("stop_jButton4"); // NOI18N
            stop_jButton4.getAccessibleContext().setAccessibleDescription("Stop the program");
            stop_jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    stop_jButton4_ActionPerformed(evt);
                }
            });


            run_jButton5.setText("Run");
            run_jButton5.setName("run_jButton5"); // NOI18N
            run_jButton5.getAccessibleContext().setAccessibleDescription("Run the program");
            run_jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    run_jButton5_ActionPerformed(evt);
                }
            });


            close_jButton6.setText("Close");
            close_jButton6.setName("close_jButton6"); // NOI18N
            close_jButton6.getAccessibleContext().setAccessibleDescription("Close this window");
            close_jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    close_jButton6_ActionPerformed(evt);
                }
            });


        general_jPanel1.setPreferredSize(new java.awt.Dimension(460,460));
        general_jPanel1.setName("general_jPanel1");

        TM_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titre1_Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N        TM_panel.setName("TM_panel"); // NOI18N

        TM_tabpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "TM_tabpanel"));
        TM_tabpanel.setName("TM_tabpanel"); // NOI18N
        TM_tabpanel.setPreferredSize(new java.awt.Dimension(280,280));
        TM_tabpanel.getAccessibleContext().setAccessibleName("TM_tabpanel");
        TM_tabpanel.addTab("STitre_TOP", TM_ST_panel);
        TM_tabpanel.addTab("STtitre2_Top", TM_STTo_panel);
        TM_tabpanel.addTab("ATitre_TOP", TM_AT_panel);


            TM_prout_RButton.setText("--prout/-p");
            TM_prout_RButton.setName("TM_prout_RButton"); // NOI18N
            TM_prout_RButton.getAccessibleContext().setAccessibleDescription("Prout option");
            TM_prout_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_prout_RButton_ActionPerformed(evt);
                }
            });


            TM_looc_box.setText("--looc/-l");
            TM_looc_box.setName("TM_looc_box"); // NOI18N
            TM_looc_box.getAccessibleContext().setAccessibleDescription("Paradise Value2");
            TM_looc_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_looc_box_ActionPerformed(evt);
                }
            });

            TM_looc_value.setName("TM_looc_value"); // NOI18N
            TM_looc_value.getAccessibleContext().setAccessibleDescription("Paradise Value2");
            TM_looc_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(8),Integer.valueOf(0),Integer.valueOf(2147483647),Integer.valueOf(1)));
            TM_looc_value.setPreferredSize(new java.awt.Dimension(115, 27));
            TM_looc_value.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    TM_looc_value_StateChanged(evt);
                }
            });

            TM_tnaihc_box.setText("--tnaihc/");
            TM_tnaihc_box.setName("TM_tnaihc_box"); // NOI18N
            TM_tnaihc_box.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_tnaihc_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_tnaihc_box_ActionPerformed(evt);
                }
            });

            TM_tnaihc_text.setName("TM_tnaihc_text"); // NOI18N
            TM_tnaihc_text.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_tnaihc_text.setText("pas cool ce programme");
            TM_tnaihc_text.setPreferredSize(new java.awt.Dimension(220, 27));
            TM_tnaihc_text.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    TM_tnaihc_text_FocusLost(evt);
                }
            });
            
        TM_ST_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STitre_TOP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        TM_ST_panel.setName("TM_ST_panel"); // NOI18N
        

            TM_ST_coolTop_box.setText("--cool-top/-c");
            TM_ST_coolTop_box.setName("TM_ST_coolTop_box"); // NOI18N
            TM_ST_coolTop_box.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_ST_coolTop_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_ST_coolTop_box_ActionPerformed(evt);
                }
            });

            TM_ST_coolTop_value.setName("TM_ST_coolTop_value"); // NOI18N
            TM_ST_coolTop_value.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_ST_coolTop_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(8),Integer.valueOf(0),Integer.valueOf(2147483647),Integer.valueOf(1)));
            TM_ST_coolTop_value.setPreferredSize(new java.awt.Dimension(115, 27));
            TM_ST_coolTop_value.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    TM_ST_coolTop_value_StateChanged(evt);
                }
            });

            TM_ST_chiant6576_box.setText("--chiant-65-76/");
            TM_ST_chiant6576_box.setName("TM_ST_chiant6576_box"); // NOI18N
            TM_ST_chiant6576_box.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_ST_chiant6576_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_ST_chiant6576_box_ActionPerformed(evt);
                }
            });

            TM_ST_chiant6576_text.setName("TM_ST_chiant6576_text"); // NOI18N
            TM_ST_chiant6576_text.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_ST_chiant6576_text.setText("pas cool ce programme");
            TM_ST_chiant6576_text.setPreferredSize(new java.awt.Dimension(220, 27));
            TM_ST_chiant6576_text.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    TM_ST_chiant6576_text_FocusLost(evt);
                }
            });
            

            TM_ST_bravo87_box.setText("--bravo-87/-b");
            TM_ST_bravo87_box.setName("TM_ST_bravo87_box"); // NOI18N
            TM_ST_bravo87_box.getAccessibleContext().setAccessibleDescription("Réussite");
            TM_ST_bravo87_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_ST_bravo87_box_ActionPerformed(evt);
                }
            });

        TM_STTo_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STtitre2_Top", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        TM_STTo_panel.setName("TM_STTo_panel"); // NOI18N
        

            TM_STTo_cool2_RButton.setText("--cool2/-c2");
            TM_STTo_cool2_RButton.setName("TM_STTo_cool2_RButton"); // NOI18N
            TM_STTo_cool2_RButton.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_STTo_cool2_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_STTo_cool2_RButton_ActionPerformed(evt);
                }
            });

            TM_STTo_cool2_value.setName("TM_STTo_cool2_value"); // NOI18N
            TM_STTo_cool2_value.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_STTo_cool2_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10),Integer.valueOf(0),Integer.valueOf(2147483647),Integer.valueOf(1)));
            TM_STTo_cool2_value.setPreferredSize(new java.awt.Dimension(115, 27));
            TM_STTo_cool2_value.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    TM_STTo_cool2_value_StateChanged(evt);
                }
            });

            TM_STTo_cool32_box.setText("--cool32/-c32");
            TM_STTo_cool32_box.setName("TM_STTo_cool32_box"); // NOI18N
            TM_STTo_cool32_box.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_STTo_cool32_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_STTo_cool32_box_ActionPerformed(evt);
                }
            });

            TM_STTo_cool32_value.setName("TM_STTo_cool32_value"); // NOI18N
            TM_STTo_cool32_value.getAccessibleContext().setAccessibleDescription("Paradise Value");
            TM_STTo_cool32_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1000),Integer.valueOf(10),Integer.valueOf(10),Integer.valueOf(1)));
            TM_STTo_cool32_value.setPreferredSize(new java.awt.Dimension(115, 27));
            TM_STTo_cool32_value.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    TM_STTo_cool32_value_StateChanged(evt);
                }
            });

            TM_STTo_chiant2_RButton.setText("--chiant2/");
            TM_STTo_chiant2_RButton.setName("TM_STTo_chiant2_RButton"); // NOI18N
            TM_STTo_chiant2_RButton.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_STTo_chiant2_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_STTo_chiant2_RButton_ActionPerformed(evt);
                }
            });

            TM_STTo_chiant2_text.setName("TM_STTo_chiant2_text"); // NOI18N
            TM_STTo_chiant2_text.getAccessibleContext().setAccessibleDescription("option nulle");
            TM_STTo_chiant2_text.setText("pas cool du tout ce programme");
            TM_STTo_chiant2_text.setPreferredSize(new java.awt.Dimension(220, 27));
            TM_STTo_chiant2_text.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    TM_STTo_chiant2_text_FocusLost(evt);
                }
            });
            

            TM_STTo_bravo2_box.setText("--bravo2/-b2");
            TM_STTo_bravo2_box.setName("TM_STTo_bravo2_box"); // NOI18N
            TM_STTo_bravo2_box.getAccessibleContext().setAccessibleDescription("Réussite");
            TM_STTo_bravo2_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TM_STTo_bravo2_box_ActionPerformed(evt);
                }
            });

        TM_AT_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ATitre_TOP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        TM_AT_panel.setName("TM_AT_panel"); // NOI18N
        

        TiMe_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titre2_Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N        TiMe_panel.setName("TiMe_panel"); // NOI18N


            TiMe_looc_box.setText("--looc/-l");
            TiMe_looc_box.setName("TiMe_looc_box"); // NOI18N
            TiMe_looc_box.getAccessibleContext().setAccessibleDescription("Paradise Value2");
            TiMe_looc_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TiMe_looc_box_ActionPerformed(evt);
                }
            });

            TiMe_looc_value.setName("TiMe_looc_value"); // NOI18N
            TiMe_looc_value.getAccessibleContext().setAccessibleDescription("Paradise Value2");
            TiMe_looc_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(8),Integer.valueOf(0),Integer.valueOf(2147483647),Integer.valueOf(1)));
            TiMe_looc_value.setPreferredSize(new java.awt.Dimension(115, 27));
            TiMe_looc_value.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    TiMe_looc_value_StateChanged(evt);
                }
            });

            TiMe_tnaihc_box.setText("--tnaihc/");
            TiMe_tnaihc_box.setName("TiMe_tnaihc_box"); // NOI18N
            TiMe_tnaihc_box.getAccessibleContext().setAccessibleDescription("option nulle");
            TiMe_tnaihc_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TiMe_tnaihc_box_ActionPerformed(evt);
                }
            });

            TiMe_tnaihc_text.setName("TiMe_tnaihc_text"); // NOI18N
            TiMe_tnaihc_text.getAccessibleContext().setAccessibleDescription("option nulle");
            TiMe_tnaihc_text.setText("pas cool ce programme");
            TiMe_tnaihc_text.setPreferredSize(new java.awt.Dimension(220, 27));
            TiMe_tnaihc_text.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    TiMe_tnaihc_text_FocusLost(evt);
                }
            });
            

            TiMe_ovarb_box.setText("--ovarb/-o");
            TiMe_ovarb_box.setName("TiMe_ovarb_box"); // NOI18N
            TiMe_ovarb_box.getAccessibleContext().setAccessibleDescription("Réussite");
            TiMe_ovarb_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TiMe_ovarb_box_ActionPerformed(evt);
                }
            });


            TiMe_q_box.setText("-q/");
            TiMe_q_box.setName("TiMe_q_box"); // NOI18N
            TiMe_q_box.getAccessibleContext().setAccessibleDescription("-q quoi");
            TiMe_q_box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    TiMe_q_box_ActionPerformed(evt);
                }
            });


    javax.swing.GroupLayout TM_ST_panelLayout = new javax.swing.GroupLayout(TM_ST_panel);
    TM_ST_panel.setLayout(TM_ST_panelLayout);
    TM_ST_panelLayout.setHorizontalGroup(
        TM_ST_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TM_ST_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TM_ST_coolTop_box)
            .addComponent(TM_ST_coolTop_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_ST_chiant6576_box)
            .addComponent(TM_ST_chiant6576_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_ST_bravo87_box)
            .addContainerGap() // truc
        )
    );
    TM_ST_panelLayout.setVerticalGroup(
        TM_ST_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TM_ST_panelLayout.createSequentialGroup()
            .addComponent(TM_ST_coolTop_box)
            .addComponent(TM_ST_coolTop_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_ST_chiant6576_box)
            .addComponent(TM_ST_chiant6576_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_ST_bravo87_box)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout TiMe_panelLayout = new javax.swing.GroupLayout(TiMe_panel);
    TiMe_panel.setLayout(TiMe_panelLayout);
    TiMe_panelLayout.setHorizontalGroup(
        TiMe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TiMe_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TiMe_looc_box)
            .addComponent(TiMe_looc_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TiMe_tnaihc_box)
            .addComponent(TiMe_tnaihc_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TiMe_ovarb_box)
            .addContainerGap()
            .addComponent(TiMe_q_box)
            .addContainerGap() // truc
        )
    );
    TiMe_panelLayout.setVerticalGroup(
        TiMe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TiMe_panelLayout.createSequentialGroup()
            .addComponent(TiMe_looc_box)
            .addComponent(TiMe_looc_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TiMe_tnaihc_box)
            .addComponent(TiMe_tnaihc_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TiMe_ovarb_box)
            .addComponent(TiMe_q_box)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout TM_STTo_panelLayout = new javax.swing.GroupLayout(TM_STTo_panel);
    TM_STTo_panel.setLayout(TM_STTo_panelLayout);
    TM_STTo_panelLayout.setHorizontalGroup(
        TM_STTo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TM_STTo_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TM_STTo_cool2_RButton)
            .addComponent(TM_STTo_cool2_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_STTo_cool32_box)
            .addComponent(TM_STTo_cool32_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_STTo_chiant2_RButton)
            .addComponent(TM_STTo_chiant2_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_STTo_bravo2_box)
            .addContainerGap() // truc
        )
    );
    TM_STTo_panelLayout.setVerticalGroup(
        TM_STTo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TM_STTo_panelLayout.createSequentialGroup()
            .addComponent(TM_STTo_cool2_RButton)
            .addComponent(TM_STTo_cool2_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_STTo_cool32_box)
            .addComponent(TM_STTo_cool32_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_STTo_chiant2_RButton)
            .addComponent(TM_STTo_chiant2_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_STTo_bravo2_box)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout TM_AT_panelLayout = new javax.swing.GroupLayout(TM_AT_panel);
    TM_AT_panel.setLayout(TM_AT_panelLayout);
    TM_AT_panelLayout.setHorizontalGroup(
        TM_AT_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TM_AT_panelLayout.createSequentialGroup()
            .addContainerGap() // truc
        )
    );
    TM_AT_panelLayout.setVerticalGroup(
        TM_AT_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TM_AT_panelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout TM_panelLayout = new javax.swing.GroupLayout(TM_panel);
    TM_panel.setLayout(TM_panelLayout);
    TM_panelLayout.setHorizontalGroup(
        TM_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TM_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TM_prout_RButton)
            .addContainerGap()
            .addComponent(TM_looc_box)
            .addComponent(TM_looc_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(TM_tnaihc_box)
            .addComponent(TM_tnaihc_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
             .addComponent(TM_tabpanel)
            .addContainerGap() // truc
        )
    );
    TM_panelLayout.setVerticalGroup(
        TM_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TM_panelLayout.createSequentialGroup()
            .addComponent(TM_prout_RButton)
            .addComponent(TM_looc_box)
            .addComponent(TM_looc_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TM_tnaihc_box)
            .addComponent(TM_tnaihc_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
             .addComponent(TM_tabpanel)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout TM_tabpanelLayout = new javax.swing.GroupLayout(TM_tabpanel);
    TM_tabpanel.setLayout(TM_tabpanelLayout);
    TM_tabpanelLayout.setHorizontalGroup(
        TM_tabpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TM_tabpanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TM_ST_panel)
            .addContainerGap()
            .addComponent(TM_STTo_panel)
            .addContainerGap()
            .addComponent(TM_AT_panel)
            .addContainerGap() // truc
        )
    );
    TM_tabpanelLayout.setVerticalGroup(
        TM_tabpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TM_tabpanelLayout.createSequentialGroup()
            .addComponent(TM_ST_panel)
            .addComponent(TM_STTo_panel)
            .addComponent(TM_AT_panel)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

        test_Pgrm_michEditor.setPreferredSize(new java.awt.Dimension(310,310));
        test_Pgrm_michEditor.addTab("test_Pgrm_mich Editor", general_jPanel1);
        test_Pgrm_michEditor.getAccessibleContext().setAccessibleName("test_Pgrm_mich");
        test_Pgrm_michEditor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                test_Pgrm_michEditorComponentShown(evt);
            }
        });
    

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(how_jButton1))
                    .addComponent(test_Pgrm_michEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(how_jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(test_Pgrm_michEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void test_Pgrm_michEditorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_test_Pgrm_michEditorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_test_Pgrm_michEditorComponentShown
    
    private void how_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }                                             
    
    private void close_jButton6_ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        this.setVisible(false);
    }                                               
    
    private void run_jButton5_ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        if (this.properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }                                             
    
    private void stop_jButton4_ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }                                              
    
    private void reset_jButton3_ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        this.display(properties);
    }                                               
    
    private void rename_jButton2_ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        properties.put("Name", this.name_jTextField1.getText());
    }                                                
    
    private void name_jTextField1_ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                 
    
    private void TM_prout_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_prout_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,TM_prout_RButton,null);
    }//GEN-LAST:event_TM_prout_RButton_ActionPerformed

    private void TM_looc_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_looc_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_looc_box,TM_looc_value);
    }//GEN-LAST:event_TM_looc_box_ActionPerformed

    private void TM_looc_value_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TM_looc_value_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_looc_box,TM_looc_value);
    }//GEN-LAST:event_TM_looc_value_StateChanged

    private void TM_tnaihc_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_tnaihc_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventText(properties,TM_tnaihc_box,TM_tnaihc_text);
    }//GEN-LAST:event_TM_tnaihc_box_ActionPerformed

    private void TM_tnaihc_text_FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TM_tnaihc_text_FocusLost
        // TODO add your handling code here:
        Util.boxEventText(properties,TM_tnaihc_box,TM_tnaihc_text);
    }//GEN-LAST:event_TM_tnaihc_text_FocusLost

    private void TM_ST_coolTop_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_ST_coolTop_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_ST_coolTop_box,TM_ST_coolTop_value);
    }//GEN-LAST:event_TM_ST_coolTop_box_ActionPerformed

    private void TM_ST_coolTop_value_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TM_ST_coolTop_value_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_ST_coolTop_box,TM_ST_coolTop_value);
    }//GEN-LAST:event_TM_ST_coolTop_value_StateChanged

    private void TM_ST_chiant6576_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_ST_chiant6576_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventText(properties,TM_ST_chiant6576_box,TM_ST_chiant6576_text);
    }//GEN-LAST:event_TM_ST_chiant6576_box_ActionPerformed

    private void TM_ST_chiant6576_text_FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TM_ST_chiant6576_text_FocusLost
        // TODO add your handling code here:
        Util.boxEventText(properties,TM_ST_chiant6576_box,TM_ST_chiant6576_text);
    }//GEN-LAST:event_TM_ST_chiant6576_text_FocusLost

    private void TM_ST_bravo87_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_ST_bravo87_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_ST_bravo87_box,null);
    }//GEN-LAST:event_TM_ST_bravo87_box_ActionPerformed

    private void TM_STTo_cool2_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_STTo_cool2_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,TM_STTo_cool2_RButton,TM_STTo_cool2_value);
    }//GEN-LAST:event_TM_STTo_cool2_RButton_ActionPerformed

    private void TM_STTo_cool2_value_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TM_STTo_cool2_value_StateChanged
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,TM_STTo_cool2_RButton,TM_STTo_cool2_value);
    }//GEN-LAST:event_TM_STTo_cool2_value_StateChanged

    private void TM_STTo_cool32_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_STTo_cool32_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_STTo_cool32_box,TM_STTo_cool32_value);
    }//GEN-LAST:event_TM_STTo_cool32_box_ActionPerformed

    private void TM_STTo_cool32_value_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TM_STTo_cool32_value_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_STTo_cool32_box,TM_STTo_cool32_value);
    }//GEN-LAST:event_TM_STTo_cool32_value_StateChanged

    private void TM_STTo_chiant2_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_STTo_chiant2_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventText(properties,TM_STTo_chiant2_RButton,TM_STTo_chiant2_text);
    }//GEN-LAST:event_TM_STTo_chiant2_RButton_ActionPerformed

    private void TM_STTo_chiant2_text_FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TM_STTo_chiant2_text_FocusLost
        // TODO add your handling code here:
        Util.buttonEventText(properties,TM_STTo_chiant2_RButton,TM_STTo_chiant2_text);
    }//GEN-LAST:event_TM_STTo_chiant2_text_FocusLost

    private void TM_STTo_bravo2_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TM_STTo_bravo2_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TM_STTo_bravo2_box,null);
    }//GEN-LAST:event_TM_STTo_bravo2_box_ActionPerformed

    private void TiMe_looc_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiMe_looc_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TiMe_looc_box,TiMe_looc_value);
    }//GEN-LAST:event_TiMe_looc_box_ActionPerformed

    private void TiMe_looc_value_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TiMe_looc_value_StateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TiMe_looc_box,TiMe_looc_value);
    }//GEN-LAST:event_TiMe_looc_value_StateChanged

    private void TiMe_tnaihc_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiMe_tnaihc_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventText(properties,TiMe_tnaihc_box,TiMe_tnaihc_text);
    }//GEN-LAST:event_TiMe_tnaihc_box_ActionPerformed

    private void TiMe_tnaihc_text_FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TiMe_tnaihc_text_FocusLost
        // TODO add your handling code here:
        Util.boxEventText(properties,TiMe_tnaihc_box,TiMe_tnaihc_text);
    }//GEN-LAST:event_TiMe_tnaihc_text_FocusLost

    private void TiMe_ovarb_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiMe_ovarb_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TiMe_ovarb_box,null);
    }//GEN-LAST:event_TiMe_ovarb_box_ActionPerformed

    private void TiMe_q_box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiMe_q_box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,TiMe_q_box,null);
    }//GEN-LAST:event_TiMe_q_box_ActionPerformed
        
    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabledFunction (boolean e) {
        this.TM_looc_box.setEnabled(e);
        if (properties.isSet(TM_looc_box.getName()) && e==true) {
            this.TM_looc_value.setEnabled(true);
        } else {
            this.TM_looc_value.setEnabled(false);
        }
        this.TM_tnaihc_box.setEnabled(e);
        if (properties.isSet(TM_tnaihc_box.getName()) && e==true) {
            this.TM_tnaihc_text.setEnabled(true);
        } else {
            this.TM_tnaihc_text.setEnabled(false);
        }
        this.TM_ST_coolTop_box.setEnabled(e);
        if (properties.isSet(TM_ST_coolTop_box.getName()) && e==true) {
            this.TM_ST_coolTop_value.setEnabled(true);
        } else {
            this.TM_ST_coolTop_value.setEnabled(false);
        }
        this.TM_ST_chiant6576_box.setEnabled(e);
        if (properties.isSet(TM_ST_chiant6576_box.getName()) && e==true) {
            this.TM_ST_chiant6576_text.setEnabled(true);
        } else {
            this.TM_ST_chiant6576_text.setEnabled(false);
        }
        this.TM_ST_bravo87_box.setEnabled(e);
        this.TM_STTo_cool32_box.setEnabled(e);
        if (properties.isSet(TM_STTo_cool32_box.getName()) && e==true) {
            this.TM_STTo_cool32_value.setEnabled(true);
        } else {
            this.TM_STTo_cool32_value.setEnabled(false);
        }
        this.TM_STTo_bravo2_box.setEnabled(e);
        this.TiMe_looc_box.setEnabled(e);
        if (properties.isSet(TiMe_looc_box.getName()) && e==true) {
            this.TiMe_looc_value.setEnabled(true);
        } else {
            this.TiMe_looc_value.setEnabled(false);
        }
        this.TiMe_tnaihc_box.setEnabled(e);
        if (properties.isSet(TiMe_tnaihc_box.getName()) && e==true) {
            this.TiMe_tnaihc_text.setEnabled(true);
        } else {
            this.TiMe_tnaihc_text.setEnabled(false);
        }
        this.TiMe_ovarb_box.setEnabled(e);
        this.TiMe_q_box.setEnabled(e);
        this.TM_prout_RButton.setEnabled(e);
        this.TM_STTo_cool2_RButton.setEnabled(e);
        if (properties.isSet(TM_STTo_cool2_RButton.getName()) && e==true) {
            this.TM_STTo_cool2_value.setEnabled(true);
        } else {
            this.TM_STTo_cool2_value.setEnabled(false);
        }
        this.TM_STTo_chiant2_RButton.setEnabled(e);
        if (properties.isSet(TM_STTo_chiant2_RButton.getName()) && e==true) {
            this.TM_STTo_chiant2_text.setEnabled(true);
        } else {
            this.TM_STTo_chiant2_text.setEnabled(false);
        }
    }
    
    
    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/
    
    private void updateSavedProperties(workflow_properties properties) {
        usp_valueANDtext (properties);
        usp_boxANDbutton (properties);
    }
    
    private void usp_valueANDtext (workflow_properties properties) {
        if (this.properties.isSet(TM_looc_value.getName())){
            this.TM_looc_value.setValue(Integer.parseInt(this.properties.get(TM_looc_value.getName())));
            this.TM_looc_value.setEnabled(false);
        }
        if (this.properties.isSet(TM_ST_coolTop_value.getName())){
            this.TM_ST_coolTop_value.setValue(Integer.parseInt(this.properties.get(TM_ST_coolTop_value.getName())));
            this.TM_ST_coolTop_value.setEnabled(false);
        }
        if (this.properties.isSet(TM_STTo_cool2_value.getName())){
            this.TM_STTo_cool2_value.setValue(Integer.parseInt(this.properties.get(TM_STTo_cool2_value.getName())));
            this.TM_STTo_cool2_value.setEnabled(false);
        }
        if (this.properties.isSet(TM_STTo_cool32_value.getName())){
            this.TM_STTo_cool32_value.setValue(Integer.parseInt(this.properties.get(TM_STTo_cool32_value.getName())));
            this.TM_STTo_cool32_value.setEnabled(false);
        }
        if (this.properties.isSet(TiMe_looc_value.getName())){
            this.TiMe_looc_value.setValue(Integer.parseInt(this.properties.get(TiMe_looc_value.getName())));
            this.TiMe_looc_value.setEnabled(false);
        }
        if (this.properties.isSet(TM_tnaihc_text.getName())){
            this.TM_tnaihc_text.setText(this.properties.get(TM_tnaihc_text.getName()));
            this.TM_tnaihc_text.setEnabled(false);
        }
        if (this.properties.isSet(TM_ST_chiant6576_text.getName())){
            this.TM_ST_chiant6576_text.setText(this.properties.get(TM_ST_chiant6576_text.getName()));
            this.TM_ST_chiant6576_text.setEnabled(false);
        }
        if (this.properties.isSet(TM_STTo_chiant2_text.getName())){
            this.TM_STTo_chiant2_text.setText(this.properties.get(TM_STTo_chiant2_text.getName()));
            this.TM_STTo_chiant2_text.setEnabled(false);
        }
        if (this.properties.isSet(TiMe_tnaihc_text.getName())){
            this.TiMe_tnaihc_text.setText(this.properties.get(TiMe_tnaihc_text.getName()));
            this.TiMe_tnaihc_text.setEnabled(false);
        }
    }
    
    private void usp_boxANDbutton (workflow_properties properties) {
        if (this.properties.isSet(TM_looc_box.getName())){
            this.TM_looc_box.setSelected(true);
            this.TM_looc_value.setEnabled(true);
        }
        if (this.properties.isSet(TM_tnaihc_box.getName())){
            this.TM_tnaihc_box.setSelected(true);
            this.TM_tnaihc_text.setEnabled(true);
        }
        if (this.properties.isSet(TM_ST_coolTop_box.getName())){
            this.TM_ST_coolTop_box.setSelected(true);
            this.TM_ST_coolTop_value.setEnabled(true);
        }
        if (this.properties.isSet(TM_ST_chiant6576_box.getName())){
            this.TM_ST_chiant6576_box.setSelected(true);
            this.TM_ST_chiant6576_text.setEnabled(true);
        }
        if (this.properties.isSet(TM_ST_bravo87_box.getName())){
            this.TM_ST_bravo87_box.setSelected(true);
        }
        if (this.properties.isSet(TM_STTo_cool32_box.getName())){
            this.TM_STTo_cool32_box.setSelected(true);
            this.TM_STTo_cool32_value.setEnabled(true);
        }
        if (this.properties.isSet(TM_STTo_bravo2_box.getName())){
            this.TM_STTo_bravo2_box.setSelected(true);
        }
        if (this.properties.isSet(TiMe_looc_box.getName())){
            this.TiMe_looc_box.setSelected(true);
            this.TiMe_looc_value.setEnabled(true);
        }
        if (this.properties.isSet(TiMe_tnaihc_box.getName())){
            this.TiMe_tnaihc_box.setSelected(true);
            this.TiMe_tnaihc_text.setEnabled(true);
        }
        if (this.properties.isSet(TiMe_ovarb_box.getName())){
            this.TiMe_ovarb_box.setSelected(true);
        }
        if (this.properties.isSet(TiMe_q_box.getName())){
            this.TiMe_q_box.setSelected(true);
        }
        if (this.properties.isSet(TM_prout_RButton.getName())){
            this.TM_prout_RButton.setSelected(true);
        }
        if (this.properties.isSet(TM_STTo_cool2_RButton.getName())){
            this.TM_STTo_cool2_RButton.setSelected(true);
            this.TM_STTo_cool2_value.setEnabled(true);
        }
        if (this.properties.isSet(TM_STTo_chiant2_RButton.getName())){
            this.TM_STTo_chiant2_RButton.setSelected(true);
            this.TM_STTo_chiant2_text.setEnabled(true);
        }
    }
    

    /*******************************************************************
     * Set the configuration properties for this object
     ******************************************************************/
    
    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        
        // Set the program properties
        this.setProperties(properties);
        
        // Update Saved Properties => usp
        this.updateSavedProperties(properties);
        
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    /*******************************************************************
     * Sets for Properties
     ******************************************************************/
    
    /**
     * Set Properties
     * @param properties
     */
    
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (this.properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues(properties);
        
        // Set the menu
        //this.menuFields();
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }
    
    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    
    private void defaultPgrmValues(workflow_properties properties) {
//        Util.getDefaultPgrmValues(properties,boolean to test the presence of a default value);
    }
    
    /*******************************************************************
     * Save Image
     ******************************************************************/
    
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton how_jButton1;           //Basic Panel
        private javax.swing.JTabbedPane test_Pgrm_michEditor; //Basic Panel
        private javax.swing.JPanel general_jPanel1;         //Basic Panel
        private javax.swing.JButton rename_jButton2;        //Basic Panel
        private javax.swing.JTextField name_jTextField1;    //Basic Panel
        private javax.swing.JLabel name_jLabel1;            //Basic Panel
        private javax.swing.JButton reset_jButton3;         //Basic Panel
        private javax.swing.JButton stop_jButton4;          //Basic Panel
        private javax.swing.JButton run_jButton5;            //Basic Panel
        private javax.swing.JButton close_jButton6;          //Basic Panel
        private javax.swing.JRadioButton TM_prout_RButton;
        private javax.swing.JCheckBox TM_looc_box;
        private javax.swing.JSpinner TM_looc_value;
        private javax.swing.JCheckBox TM_tnaihc_box;
        private javax.swing.JTextField TM_tnaihc_text;
        private javax.swing.JCheckBox TM_ST_coolTop_box;
        private javax.swing.JSpinner TM_ST_coolTop_value;
        private javax.swing.JCheckBox TM_ST_chiant6576_box;
        private javax.swing.JTextField TM_ST_chiant6576_text;
        private javax.swing.JCheckBox TM_ST_bravo87_box;
        private javax.swing.JRadioButton TM_STTo_cool2_RButton;
        private javax.swing.JSpinner TM_STTo_cool2_value;
        private javax.swing.JCheckBox TM_STTo_cool32_box;
        private javax.swing.JSpinner TM_STTo_cool32_value;
        private javax.swing.JRadioButton TM_STTo_chiant2_RButton;
        private javax.swing.JTextField TM_STTo_chiant2_text;
        private javax.swing.JCheckBox TM_STTo_bravo2_box;
        private javax.swing.JCheckBox TiMe_looc_box;
        private javax.swing.JSpinner TiMe_looc_value;
        private javax.swing.JCheckBox TiMe_tnaihc_box;
        private javax.swing.JTextField TiMe_tnaihc_text;
        private javax.swing.JCheckBox TiMe_ovarb_box;
        private javax.swing.JCheckBox TiMe_q_box;
        private javax.swing.JPanel TM_ST_panel;
        private javax.swing.JPanel TiMe_panel;
        private javax.swing.JPanel TM_STTo_panel;
        private javax.swing.JPanel TM_AT_panel;
        private javax.swing.JPanel TM_panel;
        private javax.swing.JTabbedPane TM_tabpanel;
    // End of variables declaration//GEN-END:variables
}
