/*
 *  Armadillo Workflow Platform v1.0
 *  A simple pipeline system for phylogenetic analysis
 *
 *  Copyright (C) 2009-2011  Etienne Lord, Mickael Leclercq
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package biologic.seqclasses;

import biologic.Sequence;
import configuration.Config;
import database.databaseFunction;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.Vector;

/**
 * BatchRenameJDialog
 *
 * REname selected sequences
 *
 * @author Etienne Lord
 * @since February 2011
 */
public class BatchRenameJDialog extends javax.swing.JDialog {


    databaseFunction df = new databaseFunction();    //Access to database
    Config config=new Config();                      //Configuration file
    Frame frame;                                     //parent frame

    public static int Cancel=99;
    public static int InsideParenthesis=1;
    public static int InsideBracket=2;
    public static int UseID=3;
    public static int UseAbbreviate=5;
    public static int TrimToNineCharacters=4;
    public static int RemoveToUnderScore=6;


    int choice=Cancel;

    /** Creates new form BatchRenameJDialog */
    public BatchRenameJDialog(java.awt.Frame parent) {
        super(parent, true);

        this.frame=parent;
        initComponents();
        setVisible(false);
        this.setIconImage(Config.image);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
					(screenSize.height-d.height)/2);
    }

    int display() {
        this.setVisible(true);
        return choice;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BracketjRadioButton = new javax.swing.JRadioButton();
        TrimToNineLetterjRadioButton = new javax.swing.JRadioButton();
        IDjRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ParenthesisjRadioButton = new javax.swing.JRadioButton();
        AbbreviatejRadioButton = new javax.swing.JRadioButton();
        ChangeSpacejRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Batch rename selected sequences");
        setBackground(new java.awt.Color(254, 254, 254));

        buttonGroup1.add(BracketjRadioButton);
        BracketjRadioButton.setText("Use name inside [ ] backets");

        buttonGroup1.add(TrimToNineLetterjRadioButton);
        TrimToNineLetterjRadioButton.setText("Keep first 9 letters");

        buttonGroup1.add(IDjRadioButton);
        IDjRadioButton.setText("Use sequence ID (normally from NCBI or Ensembl)");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rename");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ParenthesisjRadioButton);
        ParenthesisjRadioButton.setText("Use name inside ( ) parenthesis");

        buttonGroup1.add(AbbreviatejRadioButton);
        AbbreviatejRadioButton.setText("Use abbreviate");

        buttonGroup1.add(ChangeSpacejRadioButton);
        ChangeSpacejRadioButton.setText("Change space and comma to underscore _");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("This will rename the selected sequences according ");

        jLabel2.setText("to your selection below.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BracketjRadioButton)
                    .addComponent(ParenthesisjRadioButton)
                    .addComponent(IDjRadioButton)
                    .addComponent(AbbreviatejRadioButton)
                    .addComponent(TrimToNineLetterjRadioButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(ChangeSpacejRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BracketjRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParenthesisjRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDjRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AbbreviatejRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrimToNineLetterjRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangeSpacejRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (this.BracketjRadioButton.isSelected()) choice=this.InsideBracket;
       if (this.ParenthesisjRadioButton.isSelected()) choice=this.InsideParenthesis;
       if (this.IDjRadioButton.isSelected()) choice=this.UseID;
       if (this.TrimToNineLetterjRadioButton.isSelected()) choice=this.TrimToNineCharacters;
       if (this.AbbreviatejRadioButton.isSelected()) choice=this.UseAbbreviate;
       if (this.ChangeSpacejRadioButton.isSelected()) choice=this.RemoveToUnderScore;
       setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.choice=this.Cancel;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AbbreviatejRadioButton;
    private javax.swing.JRadioButton BracketjRadioButton;
    private javax.swing.JRadioButton ChangeSpacejRadioButton;
    private javax.swing.JRadioButton IDjRadioButton;
    private javax.swing.JRadioButton ParenthesisjRadioButton;
    private javax.swing.JRadioButton TrimToNineLetterjRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
